### ISSUE TITLE
Suggestion for re-initialize proxy after CCU was down.

### ISSUE THREAD

**Issue by tkoroscha** [danielperna84/pyhomematic#113]
Hi,
if I restart CCu2  without restart HASS, I need to reconnect Homematic `Component` to get Write access vie RPC again.

Log tells: WARNING (Thread-8) [pyhomematic._hm] ServerThread.jsonRpcLogin: Unable to open session.

If the exception keep uncaught, pyhomematic Component stops to work (no longer seen at log)

this can be fixed by the following change : "self.proxyInit()" from snippet below in _hm.py

```
    def jsonRpcLogin(self, remote):
        """Login to CCU and return session"""
        session = False
        try:
            params = {"username": self.remotes[remote][
                'username'], "password": self.remotes[remote]['password']}
            response = self._rpcfunctions.jsonRpcPost(
                self.remotes[remote]['ip'], "Session.login", params)
            if response['error'] is None and response['result']:
                session = response['result']

            if not session:
                LOG.warning(
                    "ServerThread.jsonRpcLogin: Unable to open session.")
                self.proxyInit()
        except Exception as err:
            LOG.debug(
                "ServerThread.jsonRpcLogin: Exception while logging in via JSON-RPC: %s" % str(err))
        return session
```

**Comment by danielperna84** [comment]
The `homematic.reconnect` service ([documentation](https://home-assistant.io/components/homematic/#services)) is what should be used to reconnect to the CCU. An automation can be used to trigger the reconnect.
Your solution solves the problem only partly. There can be multiple proxies, and only the one attached to the jsonRpc-stuff would know about the problem, leaving the other proxies broken. Hence it would be better to monitor a devices which reliably publishes data, and if no data has been received for a certain amount of time, call the reconnect service for the proxy for which updates stopped arriving at Home Assistant.

Of course if there's another reliable way to do this I'm open for that. But compatibility between different platforms (CCU, Homegear, RaspberryMatic etc.) is the highest priority for me.

**Comment by m0wlheld** [comment]
> The homematic.reconnect service (documentation) is what should be used to reconnect to the CCU.

Periodically or can it be event driven?

**Comment by danielperna84** [comment]
> Periodically or can it be event driven?

It can be done periodically, but that's rather unefficient. I would monitor a device in Home Assistant, and if its state hasn't changed for time X I would do the reconnect. I for example have a hm-es-tx-wm to monitor the energy of the whole house. This changes at least once every five minutes because there are always some devices consuming power. So if this doesn't change for a while, there definitely has to be a problem.
You could also monitor a brightness sensor or whatever other device you have that does change its value automatically over a certain period of time. The brightness sensor won't do much at night. So in that case I would check if the brightness hasn't changes for 5 hours or something like that.

**Comment by m0wlheld** [comment]
Re-connecting based on an unchanged value for time is a good idea. I have an outdoor thermometer and several motion/brightness sensors. Their values should not stay identical for a long time.

Another idea would be using a last-update attribute, but I am not sure, it this attribute is currently present.

**Comment by danielperna84** [comment]
The last update attribute would be pretty much the same as as the state change. Except when maybe a device really only updates attributes but not states. I don't know though if that could ever happen. If I recall correctly the attributes too are only updated when the state changes. So that wouldn't make any difference.

**Comment by m0wlheld** [comment]
I'll [ask](https://community.home-assistant.io/t/identify-unchanged-state-for-time/45706) how to do this in a Home Assistant automation. May be of interest for others, too.

**Comment by klada** [comment]
Just another cleaner suggestion:

1. Create a new sys variable "V_Last_Reboot" in the ccu2 (type string)
2. Create a new program with an empty condition and execute this HM-script with a 30 second delay:
```
var obj = dom.GetObject("V_Last_Reboot");
string now = system.Date("%d.%m.%Y %H:%M:%S");
obj.State(now);
```

Result:

- The system variable `V_Last_Reboot` is updated on every reboot
- You can then use a HA automation which monitors that variable and calls `homematic.reconnect` on any changes. This works because Homematic variables will be refreshed by HASS even after a CCU reboot (because variables are updated through polling).

**Comment by danielperna84** [comment]
It would be really great if you could add this to the [documentation](https://www.home-assistant.io/components/homematic/) of the HomeMatic component! Maybe even together with the automation that would work in HASS. 🙂

**Comment by klada** [comment]
@danielperna84 Good idea, I'll to to write a few lines of documentation over the weekend.

**Comment by klada** [comment]
@danielperna84 I have created a PR with a documentation proposal.

**Comment by danielperna84** [comment]
Since this has been added to the documentation I will close this issue now.
