### ISSUE TITLE
Test timimg is unreliable

### ISSUE THREAD

**Issue by dotlambda** [danielperna84/pyhomematic#126]
**Description of problem:**
On my (sloooow) ARMv7 machine, one of the tests is always failing because `time.sleep(2)` doesn't seem to be enough. I increased it to 10 seconds and it worked just fine.
Is there maybe a better way than just waiting for a fixed amount of time? E.g. waiting until the assertion holds.

**Traceback or log (if applicable):**
```bash
======================================================================
FAIL: test_1_pyhomematic_init (tests.test_pyhomematic.Test_1_PyhomematicBase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-python3.6-pyhomematic-0.1.39.drv-0/source/tests/test_pyhomematic.py", line 100, in test_1_pyhomematic_init
    self.assertGreater(len(devices.keys()), 0)
AssertionError: 0 not greater than 0

----------------------------------------------------------------------
Ran 4 tests in 9.720s

FAILED (failures=1)
```

**Comment by danielperna84** [comment]
In theory we could just wait until all devices are created. We have a rough extimate about this because this happens after we send the list of available devices. There is however no event that tells us when pyhomematic is really done creating all device-objects. We could let the virtual CCU fire a custom event in that case. But I also don't know how tests should be written that wait for events to happen.
Maybe it would be easier to just have some boolean flag in pyhomematic which tells us if devices are currently being created.
On the other hand: is this really necessary? If the tests pass on Travis CI, it's impossible for them to fail anywhere else. And I don't release new pyhomematic versions with failing tests.

**Comment by dotlambda** [comment]
It's necessary for people who want to test their changes on real hardware, e.g. a Raspberry Pi.

**Comment by danielperna84** [comment]
Well, instead of hardcoding the 2 seconds multiple times in the code we could have one global to hold the default delay. That way there's almost no effort for people who need to change this.
Of course it would be nicer to actually just wait until everything is ready. Maybe waiting until `len(DEVICES )` equals `self.client.devices`. But that would stop working when implementing a new device-class that may not pass the startup process. So that would be rather unreliable.

**Comment by danielperna84** [comment]
Closing this issue because the delay can now be changed [here](https://github.com/danielperna84/pyhomematic/blob/2d41f48ea1644db58a1c38b55e1c9e0fd6a2f126/tests/test_pyhomematic.py#L14).
