### ISSUE TITLE
HmIP-SRH has a lot of attributes, that are bot handled by RotaryHandleSensor

### ISSUE THREAD

**Issue by msinn** [danielperna84/pyhomematic#134]
I've got the HmIP-SRH running by now and recognize, that it has a lot of attributes, that are not handled by RotaryHandleSensor (which was created to handles the non-IP devices):

- SABOTAGE
- DUTY_CYCLE
- UNREACH
- OPERATING_VOLTAGE

and handles attributes different (instead of signaling sabotage as ERROR attribute, there is a SABOTAGE attribute and the error-attribute has a different name ERROR_CODE). 

I want to implement the additional attributes. 

Now my question: Should i create an additional Sensortype (like RotaryHandleSensorIP) or should the existing sensortype handle the variants?

**Comment by danielperna84** [comment]
Yes, an additional class for the IP variant would make sense. In that case we would also need a reference to it in Home Assistant: https://github.com/home-assistant/home-assistant/blob/ea5c336ab4bb7e8479481525ca4180093ae273e7/homeassistant/components/homematic/__init__.py#L66

**Comment by msinn** [comment]
I am now quite sure if I can help you with Home Assistant, since I don't know that software.

I am one of the developers of [https://www.smarthomeNG.de](https://www.smarthomeNG.de) and I am writing a plugin with an almost complete support for HomeMatic in SmartHomeNG. There has been a rudimentary HomeMatic support since smarthome.py (the (now dead) project we forked from). For a complete solution I decided to to base the plugin on pyhomematic.

**Comment by danielperna84** [comment]
Oh, ok, I wasn't aware of that. From a quick look at your project [Home Assistant](https://www.home-assistant.io/) is pretty similar.

In the practical use some of the internal parameters of devices aren't really needed. If you look at ioBroker you see tons of parameters that technically are important, but irrelevant to base automations on. That's why we tend to only implement what is really useful. Pretty much nobody looks at the `RSSI` for example (which is included, but sometimes incorrect because of how the RSSI works). `SABOTAGE` is important though. The old RF sensor just didn't have that.

**Comment by msinn** [comment]
On the other hand, it could be useful for me to get some of the attributes that can be defined in CCU. I would be interested in getting the room, the "Gewerk" (whatever it is called in english) or the friendly name. 

Have you an idea how I could get a hold of them?

**Comment by danielperna84** [comment]
> I agree that not all parameters are needed. But parameters like SABOTAGE, LOW_BAT and maybe OPERATING_VOLTAGE, ERROR_CODE, DUTY_CYCLE and UNREACH are of interest for home automation.
> 
> I am still undecided, if I should implement all parameters or only the useful (omitting RSSI_DEVICE, RSSI_PEER, etc.)

The way pyhomematic is supposed to be used those _less important_ values don't need to be implemented. When initializing the connection you should pass a [systemcallback](https://github.com/danielperna84/pyhomematic/blob/f47e93de2e634fbdc10b71bcfb87a73360f86aea/example.py#L13) and ideally also an [eventcallback](https://github.com/danielperna84/pyhomematic/blob/f47e93de2e634fbdc10b71bcfb87a73360f86aea/pyhomematic/_hm.py#L446). The CCU (and Homegear too) pushes state-changes of the devices to the the clients that have subscribed to the XML-RPC API. Those callbacks can be used to handle the messages and set the state of the corresponding objects your software uses. The state should __NOT__ be polled, because that actually causes the CCU to ask the device for the current state, which raises the usage of the allowed duty cycle. Anyways, all those additional less important parameters will be sent via those messages. So if your implementation is flexible you can for example just use an empty dictionary initially, and add the parameters gradually after the CCU sends the current values. The hardcoded values are there because some values need to be known directly after initalization because it may take some time until the CCU sends the states for all devices. And knowing if a switch is on or off needs to be known right from the start. Hence some important values (the one pyhomematic implements) should be queried on startup.



> On the other hand, it could be useful for me to get some of the attributes that can be defined in CCU. I would be interested in getting the room, the "Gewerk" (whatever it is called in english) or the friendly name.
> 
> Have you an idea how I could get a hold of them?

Have a look at the [resolvenames](https://github.com/danielperna84/pyhomematic/blob/f47e93de2e634fbdc10b71bcfb87a73360f86aea/pyhomematic/_hm.py#L26) parameter when initializing. It's explained here: https://www.home-assistant.io/components/homematic/#the-resolvenames-option
So pyhomematic is able to get the names of the devices already. We don't get the "Gewerke" though. These don't exist in Homegear, and essentially they are just groups. There is no point in getting the groups if the software that uses pyhomematic has it's own grouping mechanism. It might be easier at first for people who just want to test your software, but in the end people will tend to just group devices in a single place. Grouping on the CCU and in your software would be twice the work.
If you still really want to get the _Gewerke_ you should have a look at the JSON-RPC API of the CCU. It don't known from the top of my head, but I think you can get them there. The downside would be, that this won't be compatible to Homegear. And Homegear users shouldn't be ignored. I have no actual numbers. But from the threads in the Home Assistant community it feels like at least 1/6 of the users are using Homegear. Far less than the CCU, but still quite a few.

**Comment by hanzoh** [comment]
Hi,

I have just created a pull request (https://github.com/danielperna84/pyhomematic/pull/135) to fix the HmIP-SRH device. It could not report LOWBAT and ERROR because they are now called LOW_BAT and SABOTAGE in Homematic IP.

Kind regards
hanzoh

**Comment by danielperna84** [comment]
Closing this issue because:
- `UNREACH` should be covered by #161 
- `SABOTAGE` is fixed by #135 
- `DUTY_CYCLE` and `OPERATING_VOLTAGE` are not really needed in Home Assistant.
