### ISSUE TITLE
Add support for Home Assistant Entity Registry

### ISSUE THREAD

**Issue by froogl** [danielperna84/pyhomematic#152]
Home Assistant has an Entity Registry where you can "statically" assign entity ids to device serial numbers or other unique ids.

Since the name resolving through pyhomematic takes quite long when starting Home Assistant it would be cool if we could register a device in the entity registry once it's name has been fetched, so resolving that device's name can be skipped in the future. The Philips Hue platform already contains an example on how to use the Entity Registry.

Benefits people would get from this:

* Faster startup times (entities will be available instantly at startup)
* Stable entity ids (IMHO this is a huge thing)
* Renaming entity ids for usage with Home Assistant without renaming them on CCU
* Less load on CCU during HASS restarts

I think since all HM devices have a serial number this would be a good unique id to use in the Entity Registry (maybe together with the channel number, if required).

For more information see the developer docs:

https://developers.home-assistant.io/docs/en/entity_registry_index.html

**Comment by danielperna84** [comment]
I haven't used the entity registry yet. But if you don't resolve names by default all entites will be created like `sensor.leq123456` or `binary_sensor.meq654321_1`. They are already unique. If I understood the concept of the entity registry it is possible to rename these _cryptic_ entity ids statically. So to my knowledge what you want to do is already possible by just not resolving the names and specifying them in the entity registry.

**Comment by danielperna84** [comment]
I had a look at my HASS UI, and indeed it's not possible to change entity ID's via the UI. So I guess there has to be something done to provide that functionality. What that is I don't know yet.

The main problem I see is that with HomeMatic we allow two modes: _regular_ and _resolvenames_. The regular mode would be ideal for compatibility with the entity registry because the IDs always are unique already. But the _resolvenames_ mode is different, and theoretically an entity ID can be the same for different devices if the name has changed on the CCU.

So in my opinion to support the entity registry we would have to get rid of the _resolvenames_ mode, or if possible provide registry-compatibility depending on which mode the user has chosen. The big problem is, that maybe a lot of users (for good reasons) like the _resolvenames_ mode because it makes it easier getting started. But in the worst case this prohibits us from using the entity registry because we would break the setups and automations of many users, which could even be a security issue if locks are used or sensors that trigger an alarm system.

I will have to do some research regarding the entity registry. Of course anyone who knows more about the topic than me can provide information here.

**Comment by froogl** [comment]
Thanks for you quick answer. I think a user cannot simply add devices to the entity registry manually, the actual component needs to support it. In my opinion the entity registry could supplement the `resolvenames` mode, without breaking existing setups. Just like the Hue component. I could think of this workflow:

1. Discover all Homematic devices by serial number (both in *regular* mode and *resolvenames* mode)

2. Check if the serial number (*unique id*) is present in the entity registry

   - If yes, then use that entity id for the device
   - If not, when *resolvenames* mode is active, try to resolve the name to an entity id and add it to the entity registry. This way we can skip name resolving for that particular device on future HASS restarts and we get stable entity ids.


This behavior would not break existing automations, as entity_ids would stay stable. In `resolvenames` mode the "dynamic" entity_ids would be migrated to the entity registry.

**Comment by danielperna84** [comment]
The flow you propose won't work. If resolving names is enabled, it will be done before HASS starts creating entities. HASS only works with the _finished_ pyhomematic objects, and they either have the IDs or the names from the CCU.
I can of course still enable compatibility with the entity registry. But this won't improve performance in regard to resolving names. Either all or none of the names are resolved prior the HASS creating its entities.
Another problem with the resolvenames option is when you add new devices to your CCU. As you said, entities get added to the registry automatically. From what I saw after looking quickly at it all it takes is a uniqe ID property. Using the ID that we already use as the entity ID would be perfect for this. But when resolving names and adding new devices, your device shows up in HASS instantly even before you had the change to assing a name on the CCU. So when it's first seen the ID is different from what you get after setting the name on the CCU.
I don't know what would happen if we just always set the uniqe ID to the one we get when not resolving names but still resolve names. There might be a conflict when the entity ID changes outside of the scope of the registry.
So in my opinion it would be no problem to enable the registry when resolving names is disabled. With enabled resolving we would need to test what happens and maybe find some workarounds.

**Comment by danielperna84** [comment]
It seems as if all it takes to implement compatibility with the entity registry is a per-entity property _unique_id_. The can easily be made up by the devices address, channel and parameter. So in general the effort to do this won't be huge (I think). And that would even be independent of the resolved names.

However, I don't know what happens when resolving names is enabled and the device gets renamed in the CCU. This wouldn't affect the uniqe ID, but maybe the changed default enitity ID would still confuse the registry. So this aspect should be tested properly.

**Comment by danielperna84** [comment]
I have created a PR for this: https://github.com/home-assistant/home-assistant/pull/15950
This approach works perfectly for people who don't resolve names. For those that do resolve names it works too. But of course changing the name on the CCU will generate a new entity ID, and as a result a staly entry in the registry will persist. This will also happen when adding a new device to the hub and not renaming it prior to restarting Home Assistant.
To me this looks acceptable and useful. But as mentioned before, this doesn't speed up anything for people resolving names because regarding the names it's all or none.

**Comment by froogl** [comment]
Wow, this is quite cool. Can't wait to try this. I guess many people can turn off name resolving now and use custom entity IDs using the entity registry. Let's see if someone in the community comes up with a migration script which uses something like the `resolvenames` mode only once in a script in order to generate the proper entries in the registry.

**Comment by danielperna84** [comment]
Looks like this solution won't be accepted exactly because of the _uncertain_ entity IDs the `resolvenames` option generates. We'll see how this works out. For now though this won't get merged I think.

**Comment by danielperna84** [comment]
I have changed the code. It now simply exludes users that resolve names. It's just too cumbersome (if not impossible) to support both modes in parallel.
I'll see if I can come up with a helper-script that makes the transition to the _regular_ mode a little less painful.

**Comment by danielperna84** [comment]
Ok, thanks to some help there is now a solution that supports the `resolvenames` option. So you can keep it on, rename your entites over time, and then eventually turn the `resolvenames` option off.
