### ISSUE TITLE
Unknown Parameter for value key: WORKING

### ISSUE THREAD

**Issue by janbrummer** [danielperna84/pyhomematic#153]
**Description of problem:**
Several log messages within Home Assistant:

[pyhomematic.devicetypes.generic] HMGeneric.getValue: WORKING on 001118A98F2A3D:4 Exception: <Fault -5: 'Unknown Parameter for value key: WORKING'>

**Home Assistant version (if applicable):**
0.74.2

**Problem-relevant `configuration.yaml` entries and steps to reproduce:**

Standard homematic configuration for home assistant

Device is a HmIP-BROLL

**Comment by danielperna84** [comment]
I assume this message only shows up in the log while (re)starting Home Assistant and doesn't impact functionality. For the thermostat you reported a similar error it wasn't a big problem. But the cover-devices are a bit more encapsulated. So getting rid of the message would require some refactoring. If you don't experience any strange behavior I would tend to just ignore this.

**Comment by janbrummer** [comment]
Yes, this is only during startup and currently does not have any side effects. Please leave it on your list so we can get rid of it (of course it must not be now)

**Comment by FlavorFx** [comment]
Any update on this issue because error log is very prominent during startup?

**Comment by danielperna84** [comment]
No. As mentioned above, the messages during the startup of Home Assistant are just a cosmetic issue. When starting up Home Assestant thinks the device may have the `WORKING` parameter, and the CCU says _No, I dont know that_. If the message continues to popup __AFTER__ startup, then this would be an issue and the device this applies to would need to be reported. But even then it's not really a problem, because none of the Home Assistant implementation really makes use of this.

I can change to loglevel from `error` to `warning`. `info` would be too low because in some cases this could actually be an error. So `warning` would be in acceptable solution for me.

**Comment by danielperna84** [comment]
In Home Assistant 0.84 these messages will only be logged as warnings. Closing the issue.
