### ISSUE TITLE
Humidity sensor for HmIP-BWTH is missing

### ISSUE THREAD

**Issue by gethash** [danielperna84/pyhomematic#163]
Make sure you are running the latest version of pyhomematic (and Home Assistant) before reporting an issue.

_If you encounter the problem when using Home Assistant, please fill out the following information_

**Home Assistant version (if applicable):**
0.77.1

**Describe the bug**
I am using HmIP-BWTH and it works great with the current version. Today I have seen that the sensor object which I use for humidity is not there anymore.

Previously there was a sensor object named for instance

    sensor.000c9709a66be3_humidity

for every climate object. I am missing the humidity information right now and it looks all other homematic objects work great. Thanks for your work

**Expected behavior**
I am missing the humidity sensor which was created earlier

**Comment by danielperna84** [comment]
Thanks for metioning it. The problem is actually in Home Assistant. The new class hasn't been added here: https://github.com/home-assistant/home-assistant/blob/5e8a1496d7c0fd371d88f959708cef06cdbde793/homeassistant/components/homematic/__init__.py#L71
If you want to try if it fixes the issue, you can add `'IPThermostatWall230V'` to the `DISCOVER_SENSORS` sensors list. I'm 100% sure this will fix the issue.

**Comment by gethash** [comment]
Hi Daniel,

thanks for coming back. Works perfect for me! Is there already a pull request or should I create on in the home-assistant project?

Best

Bernd

**Comment by danielperna84** [comment]
I have not created one. You can do that if you want.

**Comment by danielperna84** [comment]
I took care of the PR now.
