### ISSUE TITLE
RSSI_PEER error messages in Home Assistant log

### ISSUE THREAD

**Issue by danielperna84** [danielperna84/pyhomematic#164]
**Home Assistant version (if applicable):**
0.77.2

**Describe the bug**
I get error messages regarding the RSSI_PEER parameter being unknown for HomeMatic IP devices. Looks like this in the Home Assistant log:

```
Sep 02 22:07:55 hassbian hass[779]: 2018-09-02 22:07:55 ERROR (Thread-17) [pyhomematic.devicetypes.generic] HMGeneric.getValue: RSSI_PEER on 00112233445566:0 Exception: <Fault -5: 'Unknown Parameter value for value key: RSSI_PEER'>
```

**Expected behavior**
Use the correct parameter for IP devices, or don't check RSSI at all.

**Additional context**
Probably has been introduced with this PR: https://github.com/danielperna84/pyhomematic/pull/157

**Comment by klada** [comment]
Yikes, it looks like I've messed this up when playing around with RSSI_PEER and RSSI_DEVICE. I do not have any HM-IP devices yet, so I did not notice this.

If all of the HMIP devices actually need `RSSI_DEVICE` then we could solve this through a helper class, just like `HelperWired`. I am about to pull the trigger on a set of HmIP-SWSD smoke detectors so I could start testing.

**Comment by klada** [comment]
I found [this](http://verdrahtet.info/dateien/rssi_werte.pdf) explanation about the RSSI values. The values which are displayed in the hidden CCU interface represent RSSI_DEVICE/RSSI_PEER. Most of my devices only use `RSSI_PEER`, that's why I always got _-65535_ in `RSSI_DEVICE`. If the explaination mentioned above is correct it looks like sensors most likely only have `RSSI_PEER` and actuators may also (or only) have `RSSI_DEVICE`. That's a theory, though.

At least it looks like the "correct" RSSI value is device-specific (that's also what the document says), so I am thinking that this might not be a HM-IP-only thing. We could let the actual device implemenetation decide which attribute should be used for RSSI lookups.

The referenced commit is just a suggestion, we would obviously need to plug in the appropriate helper in all of the device classes.

Pros:
- Devices can decide which value they expose for RSSI reporting.

Cons:
- We need to be very careful when it comes to multiple inheritance. For example if we plug in the `HelperRssiPeer` into the `GenericSwitch` class we cannot really use `HelperRssiDevice` for `IPSwitch` any more.


@danielperna84 What do you think? Oh, and which device is causing that error? Is it a sensor or an actuator?

**Comment by danielperna84** [comment]
In my case it's a HmIP-PSM. So an actuator.

For most of my RF devices `RSSI_PEER` is the correct one as well. But for the HmIP-PSM it is `RSSI_DEVICE`. And for the `HM-Sec-SC-2` (shutter contact) `RSSI_DEVICE` is the correct parameter as well.

The way you have done it in your commit is looking good. You can create a PR for that.

**Comment by danielperna84** [comment]
I think actively plugging in the required rssi-helper is the cleanest way. We had it broken for a bunch of devices for ages, now got them fixed, but broke others by doing that. Adding the helper where it's really needed would get rid of errors (like now with the IP-devices). And we can always patch in the helper for devices where it's missing.
So yes, to me this seems like the best approach. If it works with HASS as well I'm fine with your changes.

**Comment by klada** [comment]
OK, I have cleaned up the branch (lint fixes) and I have also tested it with Home Assistant. RSSI reports for my devices are now OK (including my new HmIP-SWSD, which needs RSSI_DEVICE). In HASS we still need to add `RSSI_DEVICE` to `HM_ATTRIBUTE_SUPPORT`.

As I said before we'll remove RSSI reporting from untested devices entirely with this PR - although adding the appropriate helper should be fairly easy now. But this is probably not too bad, because when testing my RSSI changes with HASS I found out that the RSSI_DEVICE/RSSI_PEER events are not broadcasted regularly. Maybe I haven't tested this long enough, but for me it looks like these events are only broadcasted during device discovery and then the RSSI values are never updated again :cry: 

That would mean that this whole RSSI thing is still a mess, unfortunately (at least for CCU users, I don't know how Homegear handles this) . At least the PR should fix this bug, the missing events for the RSSI attributes are a different story I think. I won't have access to my Dev machine in the next few weeks, so I cannot look into this any further at this time - I just wanted to get the PR ready.
