### ISSUE TITLE
  Add HmIP-BSL support

### ISSUE THREAD

**Issue by slankes** [danielperna84/pyhomematic#200]
eQ3 has released a new device: HmIP-BSL a "Switch Actuator for brand switches - with signal lamp". It has two LEDs which are implemented as Dimmers.

I'm trying to understand enough of pyhomematic to implement this myself but until I have succeed (or for anyone else working on this) I'm opening this ticket.

datapoints.py output for the device is here:

https://gist.github.com/slankes/7193d32445f22e70ba03471f8f33b476

**Comment by danielperna84** [comment]
I'll look into the gist during the coming days. Until then I think you can get basic switching functionality by using the [IPSwitch](https://github.com/danielperna84/pyhomematic/blob/f1482ff6fe061b5ee82d434272e36cf98764db38/pyhomematic/devicetypes/actors.py#L344) and maybe adding a case for the device name with the correct channel.
The final solution should probably also subclass the [ColorEffectLight](https://github.com/danielperna84/pyhomematic/blob/f1482ff6fe061b5ee82d434272e36cf98764db38/pyhomematic/devicetypes/actors.py#L460).

**Comment by slankes** [comment]
@danielperna84 thanks for the hint. This works for switching:

```
--- actors.py.orig	2018-12-23 11:03:38.242321783 +0100
+++ actors.py	2018-12-23 11:02:35.283853332 +0100
@@ -348,7 +348,7 @@
 
     @property
     def ELEMENT(self):
-        if "HmIP-BSM" in self.TYPE:
+        if "HmIP-BSM" or "HmIP-BSL" in self.TYPE:
             return [4]
         elif "HmIP-FSM" in self.TYPE or "HmIP-FSM16" in self.TYPE:
             return [2]
@@ -657,6 +657,7 @@
     "HMW-LC-Dim1L-DR": KeyDimmer,
     "HMIP-PS": IPSwitch,
     "HmIP-PS": IPSwitch,
+    "HmIP-BSL": IPSwitch,
     "HmIP-PCBS": IPSwitch,
     "HMIP-PSM": IPSwitchPowermeter,
     "HmIP-PSM": IPSwitchPowermeter,
```

**Comment by chr1st1ank** [comment]
I can try to assist, but the HMIP devices still feel a bit awkward to me with their many channels. It won't be an easy catch, but let's try.

First about your snippet above, @slankes. I think it works differently as you expect, because this statement is always `True`:
```
if "HmIP-BSM" or "HmIP-BSL" in self.TYPE:
```
It is evaluated as follows:
```
if bool("HmIP-BSM") or bool("HmIP-BSL" in self.TYPE):
```
and a non-empty string always evaluates to `True`. Better add another `elif` clause as with the other devices.

Now, about your new device. There is the [HMIP Device Documentation](https://www.eq-3.de/service/downloads.html?id=183) which lists the following channels for the HmIP-BSL:

| Channel number | Channel type |
| --- | --- |
| 0   | MAINTENANCE |
| 1   | KEY_TRANSCEIVER |
| 2   | KEY_TRANSCEIVER |
| 3   | SWITCH_TRANSMITTER |
| 4   | SWITCH_VIRTUAL_RECEIVER |
| 5   | SWITCH_VIRTUAL_RECEIVER |
| 6   | SWITCH_VIRTUAL_RECEIVER |
| 7   | DIMMER_TRANSMITTER |
| 8   | DIMMER_VIRTUAL_RECEIVER |
| 9   | DIMMER_VIRTUAL_RECEIVER |
| 10  | DIMMER_VIRTUAL_RECEIVER |
| 11  | DIMMER_TRANSMITTER |
| 12  | DIMMER_VIRTUAL_RECEIVER |
| 13  | DIMMER_VIRTUAL_RECEIVER |
| 14  | DIMMER_VIRTUAL_RECEIVER |
| 15  | DIMMER_WEEK_PROFILE |
 
Channels 0-6 seem to be the same as for the HmIP-BSM which is already supported. The channels 7 and 8 of the HmIP-BSM are for power measurement as it seems. So if we use the `IPSwitch` class and not its `IPSwitchPowermeter` subclass (as Daniel already suggested) we should be fine.

But then we need to add some functionality to deal with the rest of the new channels, namely 7-10 and 11-14 which seem to represent the two color lights for the upper and lower half of the switch. For them we can't take the `ColorEffectLight` (alias HM-LC-RGBW-WM) class as the basis, because there are some differences:

* Now we have two instead of only one color lights in the same device
* Color effects and dimming are not supported
* There are only 8 colors available in an integer ENUM field (BLACK, BLUE, GREEN, TURQUOISE, RED, PURPLE, YELLOW, WHITE), while the ColorEffectLight supported an HSV color model.


My suggestion would be the following approach:

1. Change the inheritance chain for the HmIP-BSM type of devices from `IPSwitch -> IPSwitchPowermeter -> IPKeySwitchPowermeter` to `IPSwitch -> IPKeySwitch -> IPKeySwitchPowermeter`, i.e. swap the last two classes in order and rename them, so that the powermeter functionality is added last.
2. Inherit from the new middle layer `IPKeySwitch` with a new class, for example `IPKeySwitchLight`.
3. If this works with the HmIP-BSL, then we use this class to add functionality for the color lights. But as there are two of them and only with eight colors, I am not yet sure how we would implement it best, in a manner that is as compatible as possible to Home Assistant. Ideas?

**Comment by danielperna84** [comment]
I have thought a bit about this. Since we can't really seem to use the usual lighting controls HASS provides (only a few colors available vs. the color picker in HASS), it might make more sense to just leave this as a switch with power monitoring.
It probably will work to use the [set_device_value](https://www.home-assistant.io/components/homematic/#services) service to control the light manually. Currently the [HomeMatic Light](https://www.home-assistant.io/components/light.homematic/) documentation only points back to the regular HomeMatic documentation. Such details for controlling the light could be placed in the relevant categories, along with useful examples. This would also allo us to de-clutter the regular documentation, which has become quite big over time.

@slankes would using the servie mentioned above be an acceptable way of controlling the lights for you?

**Comment by chr1st1ank** [comment]
Sounds reasonable. This device is a bit special in terms of controlling the color lights.
Just one more aspect from my side: The device doesn't seem to support power monitoring. That is why I suggested changing the inheritance chain. (Although I don't like it because it affects other devices which need to be tested again).

**Comment by danielperna84** [comment]
@slankes 
I have created a PR for the code that allows to control the switch and also capture the events of the buttons: https://github.com/danielperna84/pyhomematic/pull/208
Could you please modify your pyhomematic code according to the changes in the PR, __AND__ add the new device class to Home Assistant (the PR includes a link where it should go).
