### ISSUE TITLE
class name-style is mixed

### ISSUE THREAD

**Issue by dagobert** [danielperna84/pyhomematic#216]
I noticed that eg. in sensors.py you are using class names like IP.... and ...IP. Is there any reason for this or is it more like grown code.
If it is the latter I would suggest to change it to one style.

I am happy to do that for you.

**Comment by danielperna84** [comment]
Yes, makes sense. 👍

**Comment by dagobert** [comment]
You mentioned that changing the class names will cause eg. HASS to break. How is it implemented in HASS? Do they have to keep track of which class to call for eg. HMIP-BSM?

**Comment by danielperna84** [comment]
In [__init__.py](https://github.com/home-assistant/home-assistant/blob/faf7ae29b1e8be5fd4a7831ddacea7c55ca6b1f9/homeassistant/components/homematic/__init__.py#L64) you'll find this section:

```python
HM_DEVICE_TYPES = {
    DISCOVER_SWITCHES: [
        'Switch', 'SwitchPowermeter', 'IOSwitch', 'IPSwitch', 'RFSiren',
        'IPSwitchPowermeter', 'HMWIOSwitch', 'Rain', 'EcoLogic',
        'IPKeySwitchPowermeter', 'IPGarage', 'IPKeySwitch', 'IPMultiIO'],
    DISCOVER_LIGHTS: ['Dimmer', 'KeyDimmer', 'IPKeyDimmer', 'IPDimmer',
                      'ColorEffectLight'],
    DISCOVER_SENSORS: [
        'SwitchPowermeter', 'Motion', 'MotionV2', 'RemoteMotion', 'MotionIP',
        'ThermostatWall', 'AreaThermostat', 'RotaryHandleSensor',
        'WaterSensor', 'PowermeterGas', 'LuxSensor', 'WeatherSensor',
        'WeatherStation', 'ThermostatWall2', 'TemperatureDiffSensor',
        'TemperatureSensor', 'CO2Sensor', 'IPSwitchPowermeter', 'HMWIOSwitch',
        'FillingLevel', 'ValveDrive', 'EcoLogic', 'IPThermostatWall',
        'IPSmoke', 'RFSiren', 'PresenceIP', 'IPAreaThermostat',
        'IPWeatherSensor', 'RotaryHandleSensorIP', 'IPPassageSensor',
        'IPKeySwitchPowermeter', 'IPThermostatWall230V', 'IPWeatherSensorPlus',
        'IPWeatherSensorBasic', 'IPBrightnessSensor', 'IPGarage',
        'UniversalSensor', 'MotionIPV2', 'IPMultiIO'],
    DISCOVER_CLIMATE: [
        'Thermostat', 'ThermostatWall', 'MAXThermostat', 'ThermostatWall2',
        'MAXWallThermostat', 'IPThermostat', 'IPThermostatWall',
        'ThermostatGroup', 'IPThermostatWall230V'],
    DISCOVER_BINARY_SENSORS: [
        'ShutterContact', 'Smoke', 'SmokeV2', 'Motion', 'MotionV2',
        'MotionIP', 'RemoteMotion', 'WeatherSensor', 'TiltSensor',
        'IPShutterContact', 'HMWIOSwitch', 'MaxShutterContact', 'Rain',
        'WiredSensor', 'PresenceIP', 'IPWeatherSensor', 'IPPassageSensor',
        'SmartwareMotion', 'IPWeatherSensorPlus', 'MotionIPV2', 'WaterIP',
        'IPMultiIO'],
    DISCOVER_COVER: ['Blind', 'KeyBlind', 'IPKeyBlind', 'IPKeyBlindTilt'],
    DISCOVER_LOCKS: ['KeyMatic']
}
```

In the long run it could make sense to actually add something like a `hass_type` property(-list) to each class. So instead of having to add all possible classes of pyhomematic to Home Assistant, the pyhomematic classes could say "I'm a binary_sensor" or "I'm a switch and sensor". But that's not important right now. First make everything clean with all the helpers. Once that's done we can see how to gain more flexibility. Maybe the helpers just add elements to the `hass_type` based on how the helper should be presented in Home Assistant.

**Comment by danielperna84** [comment]
Closing this issue. It's only cosmetic and not being worked on apparently.
