### ISSUE TITLE
Workaround for CCU3-event-activation?

### ISSUE THREAD

**Issue by henningweiler** [danielperna84/pyhomematic#226]
So while fiddling around with all kind of things in #219, I got many things working (but not the getParamset issue yet ... will follow this up in #219)...

But maybe you have an idea concerning the following:

Based on https://www.home-assistant.io/components/homematic/#homematickeypress-events-for-homematic-ip-devices the little program is necessary for all the key channels to get the `PRESS_SHORT` and `PRESS_LONG` events. I can confirm that to be necessary for the HmIPW-DRI16/32 devices as well.

And with 90+ channels, this is a LOT of overhead (esp. for lazy computer scientists ;))

❓ Is there any shorter way of doing this?  Or could I `OR` the program trigger to select all the channels in one program to make it work?

**Comment by henningweiler** [comment]
Well ... putting all the channels in ONE program actually works.  Unfortunately, one has to do that for `PRESS_SHORT` and `PRESS_LONG` individually.  So for 90 channels, it's 180 times clicking, searching, adding.  😭

**Comment by danielperna84** [comment]
I think this is necessary because of a design-descicion eq3 has made. It's just a wild guess, but practically this implementation probably requires less resources. The CCU only forwards events that are _expected_. The ideal HomeMatic setup after all is done by linking actors and sensors directly together. That's a lot quicker, and even keeps working when the CCU is down (at least for battery powered devices).
Sending the events to the CCU for further processing without them being needed would just be a detour for the packets.
So it does make sense somehow that it's done like that. It's just not ideal for usage with external applications like Home Assistant.

Closing the issue since we can't really do anything about this (to my knowledge).

**Comment by henningweiler** [comment]
Yep, makes sense to close it, I think.  Couldn't find a programmatic way of activating the event behaviour any other way than through the program.  I share your guess on why eq-3 went down this route.
