### ISSUE TITLE
BATTERY and STATE_UNCERTAIN Flag for Keymatic

### ISSUE THREAD

**Issue by trilu2000** [danielperna84/pyhomematic#229]
Is there any chance to get the BATTERY and STATE_UNCERTAIN Flag visible in home assistant?
At the moment i get a state like:

lock.keq0856675 | locked | rssi: -180 id: KEQ0856675 interface: rf friendly_name: EG_FLR_LK supported_features: 1
-- | -- | --

For other devices, like sensors or climate i can see additional attributes, like sabotage, battery, valve, etc.
Would it be possible to get the battery flag and thestate uncertain flag for the keymatic device?

**Comment by danielperna84** [comment]
Yes, that should be possible. I didn't do the implementation back then, but I'll have a look at it.

**Comment by trilu2000** [comment]
Thanks for your quick support!
Just checked the changes. That are the attributes now:
battery: High
sabotage: No
rssi: -53
id: KEQ0856675
interface: rf
friendly_name: EG_FLR_LK
supported_features: 1

So, battery works already. I guess sabotage is the uncertain flag?

**Comment by danielperna84** [comment]
No, there should be `error` and `state_uncertain` attributes. It might be, that those only appear if the value has changed. Try manually (un)locking the KeyMatic to trigger the uncertain state and look again. But maybe there's another problem. It wouldn't be ideal if the attributes only start appearing once their value changes.

**Comment by trilu2000** [comment]
just tested - unlock and lock again, but still no uncertain flag.
Is there something i can test?

By the way - That are the attributes in channel 0:
AES_KEY, CONFIG_PENDING, DUTYCYCLE, LOWBAT, RSSI_DEVICE, RSSI_PEER, STICKY_UNREACH, UNREACH
channel 1:
DIRECTION, ERROR, INHIBIT, INSTALL_TEST, OPEN, RELOCK_DELAY, STATE, STATE_UNCERTAIN

**Comment by danielperna84** [comment]
I had another look and probably found the reason why at least `STATE_UNCERTAIN` is not added as an attribute. The HomeMatic component needs a small change to actually process the new attribute. This is done here: https://github.com/home-assistant/home-assistant/blob/5debc8828a4ea40b8e2425368139395c83421b22/homeassistant/components/homematic/__init__.py#L105
If you add `'STATE_UNCERTAIN': ['state_uncertain', {}],` to the dictionary and restart Home Assistant, it should actually work.

Depending on which Home Assistant version you are running this might also explain why you don't get the `error` attribute. This has changed with the latest release. Before that we had, as you have said, the `sabotage` attribute. But because it actually depends on the device what an error really is, this has been changed to `error` in the most recent Home Assistant release.

**Comment by trilu2000** [comment]
Thanks a lot - that was the solution for the state_uncertain flag.
The attributes still hold the sabotage flag instead of error, but that doesn't matter :-)

state uncertain   true
battery               high
sabotage           No
rssi                    -67
id                       KEQ...........
interface            rf

**Comment by danielperna84** [comment]
> The attributes still hold the sabotage flag instead of error, but that doesn't matter :-)

The value is correct though?

**Comment by trilu2000** [comment]
I can confirm that the state_uncertain flag is working, but i have no idea how i can raise an error :-)

**Comment by danielperna84** [comment]
Yeah, I guess that's hard to trigger. We'll just assume it's working. 😉

**Comment by trilu2000** [comment]
Hi Daniel,
i updated homeassistant to the latest version today and was curios why the state uncertain flag was gone, but found the reason - state_uncertain is missing in: 
https://github.com/home-assistant/home-assistant/blob/5debc8828a4ea40b8e2425368139395c83421b22/homeassistant/components/homematic/__init__.py#L105
'STATE_UNCERTAIN': ['state_uncertain', {}],
Thanks again for your support!
Cheers, Horst

**Comment by danielperna84** [comment]
If you don't mind, could you take care of that? I'm very busy currently.

**Comment by trilu2000** [comment]
done :-)
Added state_uncertain attribute to the dictionary for the Keylock device #22660
https://github.com/home-assistant/home-assistant/pull/22660#
