### ISSUE TITLE
Exception: Unknown Parameter for value key

### ISSUE THREAD

**Issue by itn3rd77** [danielperna84/pyhomematic#240]
Make sure you are running the latest version of pyhomematic (and Home Assistant) before reporting an issue.

_If you encounter the problem when using Home Assistant, please fill out the following information_

**Home Assistant version (if applicable):**
0.91.3

**Describe the bug**
During startup of Home Assistant I get the following Exceptions with ```Unknown Parameter for value key```:

1. HmIP-SWSD
  ```HMGeneric.getValue: OPERATING_VOLTAGE on 000A57099D1177:0 Exception: <Fault -5: 'Unknown Parameter for value key: OPERATING_VOLTAGE'>```
2. HMIP-SWDO
  ```HMGeneric.getValue: STATE on 0000D7098E4278:1 Exception: <Fault -5: 'Unknown Parameter value for value key: STATE'>```
```HMGeneric.getValue: RSSI_DEVICE on 0000D7098E4278:0 Exception: <Fault -5: 'Unknown Parameter value for value key: RSSI_DEVICE'>```
```HMGeneric.getValue: LOW_BAT on 0000D7098E4278:0 Exception: <Fault -5: 'Unknown Parameter value for value key: LOW_BAT'>```
```HMGeneric.getValue: OPERATING_VOLTAGE on 0000D7098E4278:0 Exception: <Fault -5: 'Unknown Parameter value for value key: OPERATING_VOLTAGE'>```
```HMGeneric.getValue: SABOTAGE on 0000D7098E4278:0 Exception: <Fault -5: 'Unknown Parameter value for value key: SABOTAGE'>```

Here is the link to the [gist](https://gist.github.com/itn3rd77/b792b63f33bad488ae7c797f45e2f1dd#file-datapoints_raspberrymatic_ccu3-json) with the datapoints

**Comment by danielperna84** [comment]
Those are just warnings and can be ignored. It is caused by classes for specific device types that inherit parameters that other similar devices usually have, but in some cases they don't.
The relevant code is here: https://github.com/danielperna84/pyhomematic/blob/master/pyhomematic/devicetypes/sensors.py
The solution would be to remove the parameters for those devices, but without removing them for other devices that use the same class.

**Comment by danielperna84** [comment]
Could you please check if some of the warnings disappear when applying the changes from [this](https://github.com/danielperna84/pyhomematic/pull/258)? I had a look at the datapoints, and those should be valid parameters for these devices. The fix aims at attaching the paramter to channel 0, which is where they are supposed to be. The posted logs point to 0 in your case already, so I'm unsure if this fix will have any effect. But because of that you shouldn't get the error in the first place actually. 🤔

**Comment by itn3rd77** [comment]
Hi,

I didn't get any of the LOW_BAT Exceptions but the following didn't go away:

`
HMGeneric.getValue: OPERATING_VOLTAGE on 000A57099D117A:0 Exception: <Fault -5: 'Unknown Parameter for value key: OPERATING_VOLTAGE'>
`
`
HMGeneric.getValue: OPERATING_VOLTAGE on 000A57099D1177:0 Exception: <Fault -5: 'Unknown Parameter for value key: OPERATING_VOLTAGE'>
`
`
HMGeneric.getValue: OPERATING_VOLTAGE on 000A57099D11A3:0 Exception: <Fault -5: 'Unknown Parameter for value key: OPERATING_VOLTAGE'>
`
`
HMGeneric.getValue: WORKING on 001118A9914CD1:4 Exception: <Fault -5: 'Unknown Parameter for value key: WORKING'>
`

Best regards
Ingo

**Comment by danielperna84** [comment]
Well, at least there are less warnings then. 👍

**Comment by danielperna84** [comment]
Are there any warnings of left of those that you have reported?
