### ISSUE TITLE
ServerProxy not deregistering and failing at next start

### ISSUE THREAD

**Issue by Koshu** [danielperna84/pyhomematic#25]
Not quite sure if this is a bug in pyhomatic or the home-assistant homematic component but i guess pyhomatic.

After complete startup the ServerThread isn'T dergistering it's proxy correctly when you close HA:

```
DEBUG:pyhomematic._hm:ServerThread.stop: Deregistering proxy
WARNING:pyhomematic._hm:Failed to deregister proxy
DEBUG:pyhomematic._hm:stop: Exception: [Errno 104] Connection reset by peer
INFO:pyhomematic._hm:Shutting down server
DEBUG:pyhomematic._hm:ServerThread.stop: Stopping ServerThread
INFO:pyhomematic._hm:Server stopped
```

And after that the next time HA is started again the initial connection fails most of the time:

```
DEBUG:pyhomematic._hm:ServerThread.__init__
INFO:pyhomematic._hm:Creating proxy. Connecting to http://127.0.0.1:2001
DEBUG:pyhomematic._hm:RPCFunctions.__init__
DEBUG:pyhomematic._hm:RPCFunctions.__init__: devices_raw = []
DEBUG:pyhomematic._hm:ServerThread.__init__: Setting up server
DEBUG:pyhomematic._hm:ServerThread.__init__: Registering RPC functions
INFO:pyhomematic._hm:Starting server at http://127.0.0.1:8222
DEBUG:pyhomematic._hm:ServerThread.proxyInit: init(http://127.0.0.1:8222, 'homeassistant')
DEBUG:pyhomematic._hm:proxyInit: Exception: [Errno 111] Connection refused
WARNING:pyhomematic._hm:Failed to initialize proxy
CRITICAL:pyhomematic.connection:Failed to start server
DEBUG:pyhomematic.connection:
DEBUG:pyhomematic._hm:ServerThread.stop: Deregistering proxy
WARNING:pyhomematic._hm:Failed to deregister proxy
DEBUG:pyhomematic._hm:stop: Exception: [Errno 111] Connection refused
INFO:pyhomematic._hm:Shutting down server
DEBUG:pyhomematic._hm:ServerThread.stop: Stopping ServerThread
INFO:pyhomematic._hm:Server stopped
```

Starting it a third time works correctly again (until you close it and it start from the beginning)

Is it correct, that the deregistering code of _hm.py line 336 contains an "init"? Shouldn't it be "close" or something?

```
    def stop(self):
        """To stop the server we de-init from the CCU / Homegear, then shut down our XML-RPC server."""
        if self.proxy:
            LOG.debug("ServerThread.stop: Deregistering proxy")
            try:
>>this one>>    self.proxy.init("http://%s:%i" % (self._local, int(self._localport))) 
            except Exception as err:
                LOG.warning("Failed to deregister proxy")
                LOG.debug("stop: Exception: %s" % str(err))
```

Thanks

**Comment by danielperna84** [comment]
I assume you are using homegear, since you are connection to localhost. Do the homegear logs provide any useful output?

The "init" while de-registering is correct. The Process is as follows:

pyhomematic connects to CCU with init and some identifier (_homeassistant_ in HA, _pyhomematic_ by default). The identifier later always is referenced as _interface_id_. The reason is, that multiple clients may connect to the CCUs XML-RPC, and this identifier ensures, that the clients can validate that they are the correct recipient.
When shutting down pyhomematic, it has to tell the CCU that it can stop pushing data for the respective client. This is done by using the init-method without an _interface_id_. From the initial init the CCU knows the IP + identifier of the client. Leaving out the identifier when init'ing again is enough for the CCU to know that this is acutally a de-register for the IP that is calling the init-method.

Currently we actually don't verify the _interface_id_ when handeling messages we receive. I've created an issue for this.

But I'm uncertain if that really is the cause for this issue. It might be. If you have multiple HAs running (each idenfiying themselves as _homeassistant_ to the CCU), shutting down one of them may break the connection of the other HA using the some identifier, which would prove that the second init is doing what it is supposed to do.

So, do you have multiple HAs running while testing?

**Comment by Koshu** [comment]
You are right, I'm running homegear version 0.6.0-1340 on the same machine (Ubuntu 16.04).

Only one instance of HA is running.

I looked at the homegear logs (should have done that sooner) and found a few things:

1. When HA connects HG has trouble with the system.listMethods call. I actually remember that one. I ran into the exact same problem when i started to write an xmlrpc connector for homegear myself (before I noticed that you guys where already doing that and are way ahead of me ;) ). If i remember correctly, the reason is, that homegear additionally passes the interface_id to listMethods. The xmlrpc implementation of python, however, doesn't expect that parameter if you use the default listMethod implementation. I'm not sure who is at fault there. The xmlrpc documentation doesn't notice an id as far as I know. Would be interesting what the original CCU does. My solution at that time was to write listMethod myself. Not sure how important that function is to homegear but it is probably not the reason for issue 2.


2. Homegear actually breaks down with an segmentation fault when HA disconnects. Since it restarts automatically i didn't notice and this might be the reason why HA isn't able to connect on next startup. Impatient like i am, i probably restarted HA before HG was ready again. Now the question is why HG breaks in the first place. So, there is obviously a problem in homegear and i will try to look into that next. I added the important lines from the logs and error-logs from the connect and disconnect attempts.


3. (Looking at the logs, is it correct that there are so many clients connecting (all from HA)?)

[homgear_connect_log.txt](https://github.com/danielperna84/pyhomematic/files/333660/homgear_connect_log.txt)

[homgear_disconnect_log.txt](https://github.com/danielperna84/pyhomematic/files/333661/homgear_disconnect_log.txt)

[homgear_connect_error.txt](https://github.com/danielperna84/pyhomematic/files/333662/homgear_connect_error.txt)

[homgear_disconnect_error.txt](https://github.com/danielperna84/pyhomematic/files/333663/homgear_disconnect_error.txt)

**Comment by danielperna84** [comment]
I got the error with listMethods myself, and for now I just decided to ignore that, since HG does not conform to the official API. Hence I think it is safe to just ignore the error. We could modify pyhomematics listMethods, but then we have to make sure the CCU still works. Which might not, since it does not provide that extra parameter. This has to be tested. I'll create an issue for that as well.

Regarding your connect_log:
How many devices do you have paired with homegear? My first guess would be, that the clients correspond to each proxy-connection used while setting up the HA-entities (fetch their current state). By default a delay of 0.5s is used, which roughly matches the timestamps in your logfile.

Regarding your disconnect_log:
I don't have any similar messages in my log, and especially the last couple days if started and stopped HA very often. Do you have any special configuration in HG? Mine is default, with just my HM-CFG-LAN configured. Since HG can usw MQTT, Philips Hue etc., that's something you might have which I don't.

Regarding your disconnect_error:
This looks like a problem within HG. But I don't know C++. @pvizeli can you tell us something about this?

**Comment by pvizeli** [comment]
HG trow an exeption on disconnect an want to be restarting on core process. I think the exption will catch from core and they can restart this process. That's not really a nice program handling.

Thats is a bug from HG and not from pyhomematic.

**Comment by danielperna84** [comment]
@Koshu any news on this? Even though it's not a bug in pyhomematic, it might be good to know how this problem can be solved.

**Comment by Koshu** [comment]
Nearly forgot about that one. Haven't solved but just opened an issue for homegear:

[https://github.com/Homegear/Homegear/issues/253](https://github.com/Homegear/Homegear/issues/253)

**Comment by Koshu** [comment]
@hfedcba fixed the issue in homegear in the latest nightly. Seems to fix the error of HA, too.
