### ISSUE TITLE
Connect HomeMatic with two HA instances

### ISSUE THREAD

**Issue by noxhirsch** [danielperna84/pyhomematic#263]
**Is your feature request related to a problem? Please describe.**
Recently I set up a second Home Assistant instance which jumps in, when I restart my main instance or if my main instance have problems. I connected the second instance with my CCU3, so I can control my switches and get keypresses from the remote controls.
Now I can control my switches from both HA instances, but only the last rebooted instance gets the event updates from HM. While it's fine that only one instance gets the events (I even prefer that way), it would be useful to tell the CCU quickly to send the events to the second HA instance. I thought `homematic.reconnect` would do the trick, but nothing happens - I also can't see anything related in the debug log.

**Describe the solution you'd like**
Maybe the reconnect service doesn't reconnect if it's already connected? A complete reconnect might be the solution for my problem. Then I could trigger it on my second instance when the main instance gets offline.

**Describe alternatives you've considered**
Sadly nothing better occured to me, but maybe you have a better solution?

**Additional context**

**Comment by danielperna84** [comment]
I assume you also sync your configuration to the other server. The _problem_ is, that Home Assistant itentifies itself as _homeassistant-wireless_ if you have configured the name for the wireless host as _wireless_. When doing this, the IP is also transmitted. So essentially the CCU thinks the IP for this particular RPC-client has changed.  
You could work around this by renaming the host in your Home Assistant configuration to someting different for each host. But that makes syncing the config a bit more difficult.  
The ideal solution would be, the in the Home Assistant component a unique but stable ID would be appended to the _interface id_ (that's how it's called in HomeMatic terms). I'm unsure if Home Assistant has something like that. Using a random string could potentially be bad because in cases of crashes et. al. stale connections would remain on the CCU because Home Assistant could not unsubscribe for events if it doesn't know which ID it had before.

**Comment by noxhirsch** [comment]
That was easier than I thought! I don't sync the config, because I want my backup instance just to cover the basic control of my smart home. So renaming the hostname is no problem at all (I always assumed, that it has to be named "wireless" etc).

Thank you very much for your fast help! :)
