### ISSUE TITLE
HMGeneric.getValue: No entity for LOWBAT on HM-Sec-SD (Rauchmelder)

### ISSUE THREAD

**Issue by jorismocka** [danielperna84/pyhomematic#279]
Sorry but I have an battery state issue too. 
hass.io Version 0.103.6 but Prroblems exists since 0.104 or 5 I think.

low bat entity of all HM-Sec-SD is not available, but e. g. the Door sensor is still working, both implemented at the same time. 

![grafik](https://user-images.githubusercontent.com/59694326/72071404-01ace480-32ec-11ea-80a4-45951689e40b.png)

![grafik](https://user-images.githubusercontent.com/59694326/72071559-5d776d80-32ec-11ea-96c6-fbc6eeb323af.png)

Smoke detector itself works without any problem but low bat is not available at all. Sorry no relevant logs in home-assistant.log

Thank you very much for your Support!
Regards
Joris

**Comment by danielperna84** [comment]
That's because the device doesn't have `LOWBAT`. You can see this if you look at the [documentation](https://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/hm_devices_Endkunden.pdf). Before the last patch we have assumed the device has that attribute, but it didn't have any real value since the device doesn't report it. But the entity for the attribute has been created anyways. Now with the new version the entity is not created anymore because the device doesn't have the value. So essentially having the entity you have is the bug, and now it's fixed. Now you just have to get rid if the entity.

**Comment by jorismocka** [comment]
Ah, Okay - thank you very much for the very fast answer and sorry for the effort I caused. 
Thank you also for your work which I really appriciate!

**Comment by flexkra** [comment]
I'm sorry to reopen this issue but the HM-Sec-SD does infact have a LOWBAT attribute. 
I overlooked the code and with the xml-rpc server you query `config/xmlapi/devicelist.cgi` where it is not reported but if you look at `config/xmlapi/statelist.cgi` the LOWBAT attribute along with others are reported on channel 0 (MAINTENANCE) for a HM-Sec-SD devices. I assume it's the same for the other battery powered devices.
