### ISSUE TITLE
SSL/TLS for callback server

### ISSUE THREAD

**Issue by kbabioch** [danielperna84/pyhomematic#312]
**Is your feature request related to a problem? Please describe.**
pyhomatic supports encrypted and authenticated connections to Homematic via SSL/TLS. There are several settings (e.g. `port`, `ssl`, `verify_ssl`, etc.). This ensures that credentials are secured from eavesdropping, as well as ensures authenticity and integrity.

However, it seems that the server that receives the responses from Homematic is always made available only via HTTP - without any encryption.

At the very least this will expose sensor/event data from Homematic to eavesdropping and other attacks.

**Describe the solution you'd like**
There hsould be an option to make the server hosted for receiving responses from Homematic (callbacks) available via SSL/TLS.

**Describe alternatives you've considered**
There is no alternative, SSL/TLS should be supported bi-directional.

**Additional context**
Not sure whether Homematic itself supports SSL/TLS in this capacity. If not, it needs to be requested / implemented.

**Comment by danielperna84** [comment]
The _problem_ I see with this is that, due to the local nature, only self-signed certificates would be useful. Or a private CA. In both cases it would be required to add the CA/certificate to the trust of the CCU. I didn't find a way to do that within the CCUs UI, and doing it manually via SSH might not be the best solution as well.
So as a result of that the alternative would be, that the CCU simply doesn't verify the certificate of the XML-RPC endpoint it connects to. Of course that generally would provide an encrypted connection. But in terms of eavesdropping we wouldn't gain anything. After all anybody could MITM the connection with another certificate as it won't be verified for authenticity anyway. 🤷‍♂️ 

I do see the point you're making, and I agree that it makes sense theoretically. But I doubt there would be a practical benefit.

**Comment by kbabioch** [comment]
> The _problem_ I see with this is that, due to the local nature, only self-signed certificates would be useful.

No, I'm using a public certificate from Let's Encrypt for my Homematic. And **no, it is not exposed to the Internet**. You can get certificates via other manes (DNSAPI, etc.) and upload them to your Homematic (Raspberrymatic).

> I didn't find a way to do that within the CCUs UI, and doing it manually via SSH might not be the best solution as well.

That doesn't mean that there should not be support for it. We can request / add such a feature into Homematic. I'm uploading my certificate via SSH currently. @jens-maus seems to be quite active in this area.

> But in terms of eavesdropping we wouldn't gain anything.

Well, in terms of eavesdropping (= passive) you gain a lot by only having encryption (without authentication).

> After all anybody could MITM the connection with another certificate as it won't be verified for authenticity anyway. man_shrugging

You're right, but this requires an **active** attack (MitM), which is more difficult to do then just "listening in". It is still trivial to do for anyone with tools / skills, but its more than just capturing traffic via Wireshark. Having SSL/TLS - even without proper authentication - is still better than nothing, but obviously having proper certificate verification on both ends is even better.

Just consider the bulk data collection by NSA and other agencies. They were only able to collect everything, because it was trivial to do. I'm sure they can still actively attack specific targets, if they choose to do so (e.g. get rogue certificates from one of the many CAs), but they are no longer able to "collect everything", because most of the web is using HTTPS now.

> I do see the point you're making, and I agree that it makes sense theoretically. But I doubt there would be a practical benefit.

There is a practical benefit, as we should assume anything non-encrypted to be "technical debt" and not simply accept it as "good enough". Proper SSL/TLS should be a required feature in all appliances like this, not something that is put there after the fact halfheartedly - like it currently is the case.

**Comment by danielperna84** [comment]
> No, I'm using a public certificate from Let's Encrypt for my Homematic. And **no, it is not exposed to the Internet**. You can get certificates via other means (DNSAPI, etc.) and upload them to your Homematic (Raspberrymatic) without exposing them to the Internet. I'm doing this a lot for privately hosted appliances / assets.

Sure. But that then also requires a properly configured DNS. Which you probably have. But most users will have a generic router where they can't configure their local hosts that _precisely_.

> That doesn't mean that there should not be support for it. We can request / add such a feature into Homematic. I'm uploading my certificate via SSH currently. @jens-maus seems to be quite active in terms of Homematic development / integration.

Well, __I__ don't want to build something (for free) that only 2-3 people will be using as long it's not an official feature of the CCU. __IF__ this gets added to the CCU (and not just RaspberryMatic), I would implement it. This of course is under the assumption, that with the current implementation the CCU would abort connections that don't pass the certificate verification.

> Well, in terms of eavesdropping (= passive) you gain a lot by only having encryption (without authentication).

If authentication for the XML-RPC API isn't enabled (and the _firewall_ open) on the CCU, any client can subscribe to read all the data. And if the firewall is closed, devices on the CCU can't be controlled. _Fake_ events could be sent to the HA-side (because it doesn't require authentication), encryption doesn't help here as well. And keep in mind: HA --> CCU can be encrypted already. That's were currently credentials are transmitted (if authentication is enabled).  
That being said, this all assumes your network has been compromised already. I agree that still it makes sense to encrypt. But if someone with malicious intentions is able to sniff, you actually have a bigger problem somewhere else.

> You're right, but this requires an **active** attack (MitM), which is more difficult to do then just "listening in". It is still trivial to do for anyone with tools / skills, but its more than just capturing traffic via Wireshark.

If an attacker managed to get on your network, then this won't pose a problem for him.

> Having SSL/TLS - even without proper authentication - is still better than nothing, but obviously having proper certificate verification on both ends is even better.

I agree, that the gathered information _can_ have some value. But the effort to implement this for only a few people who would use this seems too high given all the obstacles that would need to be worked around. Adding TLS support might not be as easy as it sounds. The Server-module Python provides doesn't have support for that built in, so it would have to be applied to it manually, probably by wrapping the socket it the best case.

> There is a practical benefit, as we should assume anything non-encrypted to be "technical debt" and not simply accept it as "good enough". Proper SSL/TLS should be a required feature in all appliances like this, not something that is put there after the fact halfheartedly - like it currently is the case.
> 
> Homematic seems to be a really crappy in terms of software development, privilege model and system integration. A somewhat secure setup should definitely use SSL/TLS (plus many additional things like putting the appliance outside of your actual LAN, etc.).

I agree with that as well. But again, this only makes sense if the CCU supports this in the first place.

One more thing: you also have to consider what would be accepted on the Home Assistant side. The only thing I can imagine to be accepted would be, that the certificate that is already being used for Home Assistant itself would also be passed to pyhomematic. That would already break the solution using a dedicated certificate where the hostname resolves locally, because typically these certificates contain the public hostname. So in my opinion the only real chance of this happening is, if the CCU doesn't verify certificates. And I have to say: I'd trust a CCU even less if it doesn't verify certificates.

**Comment by danielperna84** [comment]
Closing this issue. If at all, this feature should be implemented in [hahomematic](https://github.com/danielperna84/hahomematic).
