### ISSUE TITLE
Support for device: HMIP-HDM1 (blinds)

### ISSUE THREAD

**Issue by bhessen** [danielperna84/pyhomematic#333]
**Is your feature request related to a problem? Please describe.**
I would like to have support for my new blinds.

**Describe the solution you'd like**
Device support like all the other devices ;-)

**Describe alternatives you've considered**
-

**Additional context**
output of get_device_data.py: 
https://gist.github.com/bhessen/d817339753040b6afc714c4282b04ed9
https://gist.github.com/bhessen/9b65dd9517b2a91288d0a54f58b2006b

**Comment by danielperna84** [comment]
Please first give it a try yourself. I currently don't have much time to work on this project. Instructions on how to get started with development can be found [here](https://github.com/danielperna84/pyhomematic/wiki/Contributing-and-development-for-pyhomematic).

**Comment by bhessen** [comment]
Hi, I tried my best but I am a bit stuck here. Any help or pointer in the right direction is much appreciated.

I did the following:
1. run the script get_device_data.py. Output see above.
2. modified ../pyhomematic/devicetypes/actors.py:
     added line 896: 
`"HmIP-HDM1": IPKeyBlindTilt,`
(my blinds are not 'tilt'able, but they do have a 'LEVEL_2' attribute which is only present in 'HelperActorBlindTilt' which is referenced by 'IPKeyBlindTilt'.
3. started logging in configuration.yaml:
```
logger:
  default: warning
  logs:
    homeassistant.core: warning
    pyhomematic: debug
    homeassistant.components.homematic: debug
```
4. restart home assistant
5. in the log I can see entries like this:
```
2020-10-02 20:57:26 DEBUG (SyncWorker_0) [pyhomematic.devicetypes.generic] HMGeneric.getValue: address = '0000448151013F:0', key = 'RSSI_PEER'
2020-10-02 21:13:48 DEBUG (Thread-5) [pyhomematic._hm] RPCFunctions.event: interface_id = homeassistant-ip, address = 0000448151013F:0, value_key = CONFIG_PENDING, value = False
2020-10-02 21:13:48 INFO (Thread-5) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0000448151013F:0, interface_id=homeassistant-ip, key=CONFIG_PENDING, value=False
2020-10-02 21:13:48 DEBUG (Thread-5) [pyhomematic._hm] RPCFunctions.event: interface_id = homeassistant-ip, address = 0000448151013F:0, value_key = DUTY_CYCLE, value = False
2020-10-02 21:13:48 INFO (Thread-5) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0000448151013F:0, interface_id=homeassistant-ip, key=DUTY_CYCLE, value=False
2020-10-02 21:13:48 DEBUG (Thread-5) [pyhomematic._hm] RPCFunctions.event: interface_id = homeassistant-ip, address = 0000448151013F:0, value_key = LOW_BAT, value = False
2020-10-02 21:13:48 INFO (Thread-5) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0000448151013F:0, interface_id=homeassistant-ip, key=LOW_BAT, value=False
2020-10-02 21:13:48 DEBUG (Thread-5) [pyhomematic._hm] RPCFunctions.event: interface_id = homeassistant-ip, address = 0000448151013F:0, value_key = UNREACH, value = False
2020-10-02 21:13:48 INFO (Thread-5) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0000448151013F:0, interface_id=homeassistant-ip, key=UNREACH, value=False
2020-10-02 21:13:48 DEBUG (Thread-5) [pyhomematic._hm] RPCFunctions.event: interface_id = homeassistant-ip, address = 0000448151013F:0, value_key = RSSI_DEVICE, value = -70
2020-10-02 21:13:48 INFO (Thread-5) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0000448151013F:0, interface_id=homeassistant-ip, key=RSSI_DEVICE, value=-70
2020-10-02 21:13:48 DEBUG (Thread-5) [pyhomematic._hm] RPCFunctions.event: interface_id = homeassistant-ip, address = 0000448151013F:0, value_key = OPERATING_VOLTAGE_STATUS, value = 0
2020-10-02 21:13:48 INFO (Thread-5) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0000448151013F:0, interface_id=homeassistant-ip, key=OPERATING_VOLTAGE_STATUS, value=0
2020-10-02 21:13:48 DEBUG (Thread-5) [pyhomematic._hm] RPCFunctions.event: interface_id = homeassistant-ip, address = 0000448151013F:0, value_key = OPERATING_VOLTAGE, value = 12.6
2020-10-02 21:13:48 INFO (Thread-5) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0000448151013F:0, interface_id=homeassistant-ip, key=OPERATING_VOLTAGE, value=12.6
2020-10-02 21:13:48 DEBUG (Thread-5) [pyhomematic._hm] RPCFunctions.event: interface_id = homeassistant-ip, address = 0000448151013F:0, value_key = ERROR_CODE, value = 0
2020-10-02 21:13:48 INFO (Thread-5) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0000448151013F:0, interface_id=homeassistant-ip, key=ERROR_CODE, value=0
2020-10-02 21:13:48 DEBUG (Thread-5) [pyhomematic._hm] RPCFunctions.event: interface_id = homeassistant-ip, address = 0000448151013F:1, value_key = SECTION_STATUS, value = 0
2020-10-02 21:13:48 INFO (Thread-5) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0000448151013F:1, interface_id=homeassistant-ip, key=SECTION_STATUS, value=0
2020-10-02 21:13:48 DEBUG (Thread-5) [pyhomematic._hm] RPCFunctions.event: interface_id = homeassistant-ip, address = 0000448151013F:1, value_key = LEVEL_2_STATUS, value = 5
2020-10-02 21:13:48 INFO (Thread-5) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0000448151013F:1, interface_id=homeassistant-ip, key=LEVEL_2_STATUS, value=5
2020-10-02 21:13:48 DEBUG (Thread-5) [pyhomematic._hm] RPCFunctions.event: interface_id = homeassistant-ip, address = 0000448151013F:1, value_key = LEVEL_STATUS, value = 0
2020-10-02 21:13:48 INFO (Thread-5) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0000448151013F:1, interface_id=homeassistant-ip, key=LEVEL_STATUS, value=0
2020-10-02 21:13:48 DEBUG (Thread-5) [pyhomematic._hm] RPCFunctions.event: interface_id = homeassistant-ip, address = 0000448151013F:1, value_key = PROCESS, value = 0
2020-10-02 21:13:48 INFO (Thread-5) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0000448151013F:1, interface_id=homeassistant-ip, key=PROCESS, value=0
2020-10-02 21:13:48 DEBUG (Thread-5) [pyhomematic._hm] RPCFunctions.event: interface_id = homeassistant-ip, address = 0000448151013F:1, value_key = LEVEL, value = 0.0
2020-10-02 21:13:48 INFO (Thread-5) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0000448151013F:1, interface_id=homeassistant-ip, key=LEVEL, value=0.0
2020-10-02 21:13:48 DEBUG (Thread-5) [pyhomematic._hm] RPCFunctions.event: interface_id = homeassistant-ip, address = 0000448151013F:1, value_key = SECTION, value = 0
2020-10-02 21:13:48 INFO (Thread-5) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0000448151013F:1, interface_id=homeassistant-ip, key=SECTION, value=0
2020-10-02 21:13:48 DEBUG (Thread-5) [pyhomematic._hm] RPCFunctions.event: interface_id = homeassistant-ip, address = 0000448151013F:1, value_key = ACTIVITY_STATE, value = 3
2020-10-02 21:13:48 INFO (Thread-5) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0000448151013F:1, interface_id=homeassistant-ip, key=ACTIVITY_STATE, value=3
2020-10-02 21:13:48 DEBUG (Thread-5) [pyhomematic._hm] RPCFunctions.event: interface_id = homeassistant-ip, address = 0000448151013F:2, value_key = WEEK_PROGRAM_CHANNEL_LOCKS, value = 0
2020-10-02 21:13:48 INFO (Thread-5) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0000448151013F:2, interface_id=homeassistant-ip, key=WEEK_PROGRAM_CHANNEL_LOCKS, value=0
```
But I do not get any new entities in home assistant. What am I doing wrong here?

**Comment by danielperna84** [comment]
Are you sure they're not just hidden because you haven't assigned them to a lovelace view? Since the events are being received, HA does know about the device in some form.

**Comment by bhessen** [comment]
> Are you sure they're not just hidden because you haven't assigned them to a lovelace view?

I am still quite fresh to home assistant: I checked all filter boxes in the "entities" section. Should be enough, right? Still no new entries...

**Comment by bhessen** [comment]
Hi, I managed (after a lot of trying...) to get it to work.

If you want to integrate it, here is what worked for me (not the most elegant but works):

```
from pyhomematic.devicetypes.helper import (
    HelperWorking, HelperActorState, HelperActorLevel, HelperActorBlindTilt, HelperActionOnTime,
    HelperActionPress, HelperEventRemote, HelperWired, HelperRssiPeer, HelperRssiDevice, HelperDeviceTemperature, HelperLowBatIP)


class IPBlindErfal(GenericBlind, HelperRssiDevice, HelperLowBatIP):
    """
    Blind switch that raises and lowers roller shutters or window blinds.
    """
    def __init__(self, device_description, proxy, resolveparamsets=False):
        super().__init__(device_description, proxy, resolveparamsets)
        # init metadata
        self.ATTRIBUTENODE.update({"ACTIVITY_STATE": [1],
                                #   "LEVEL_2_STATUS": [1],
                                   "LEVEL_STATUS":   [1],
                                #   "PROCESS": [1],            # Integrate HelperWorking and overwrite "is_working"
                                #   "SECTION": [1],
                                #   "SECTION_STATUS": [1]
                                })
        self.WRITENODE.update({"LEVEL": [1],
                            #   "LEVEL_2": [1],
                            #   "SHADING_SPEED": [1]
                            })
        self.ACTIONNODE.update({"STOP": [1]})
    
        LOG.debug("HMActors.IPBlindErfal, address=%s, Attributenodes: %s", self.ADDRESS, str(self.ATTRIBUTENODE.keys()) )
        LOG.debug("HMActors.IPBlindErfal address=%s, Actionnodes: %s", self.ADDRESS, str(self.ACTIONNODE.keys()) )
        LOG.debug("HMActors.IPBlindErfal address=%s,  Writenodes: %s", self.ADDRESS, str(self.WRITENODE.keys()) )

DEVICETYPES = {
    "HM-LC-Bl1-SM": Blind,
    "HM-LC-Bl1-SM-2": Blind,
    "HM-LC-Bl1-FM": Blind,
    "HM-LC-Bl1-FM-2": Blind,
    "HM-LC-Bl1PBU-FM": Blind,
    "HM-LC-Bl1-PB-FM": Blind,
    "HM-LC-Ja1PBU-FM": Blind,
    "ZEL STG RM FEP 230V": Blind,
    "263 146": Blind,
    "263 147": Blind,
    "HM-LC-BlX": Blind,
    "HM-Sec-Win": Blind,
    "HmIP-HDM1": IPBlindErfal, #########################################################
    "HmIP-BROLL": IPKeyBlind,
    "HmIP-FROLL": IPKeyBlind,
    "HmIP-BBL": IPKeyBlindTilt,
    "HmIP-FBL": IPKeyBlindTilt,
    "HmIP-DRBLI4": IPKeyBlindMulti,
    "HM-LC-Dim1L-Pl": Dimmer,
    "HM-LC-Dim1L-Pl-2": Dimmer,
    "HM-LC-Dim1L-Pl-3": Dimmer,
    "HM-LC-Dim1L-CV": Dimmer,
    "HM-LC-Dim1L-CV-2": Dimmer,
    "HM-LC-Dim1T-Pl": Dimmer,
    "HM-LC-Dim1T-Pl-2": Dimmer,
    "HM-LC-Dim1T-Pl-3": Dimmer,
    "HM-LC-Dim1T-CV": Dimmer,
    "HM-LC-Dim1T-CV-2": Dimmer,
    "HM-LC-Dim1T-DR": Dimmer,
    "HM-LC-Dim1T-FM": Dimmer,
    "HM-LC-Dim1T-FM-2": Dimmer,
    "HM-LC-Dim1T-FM-LF": Dimmer,
    "HM-LC-Dim1PWM-CV": Dimmer,
    "HM-LC-Dim1PWM-CV-2": Dimmer,
    "HM-LC-Dim1TPBU-FM": Dimmer,
    "HM-LC-Dim1TPBU-FM-2": Dimmer,
    "HM-LC-Dim2L-CV": Dimmer,
    "HM-LC-Dim2L-SM": Dimmer,
    "HM-LC-Dim2L-SM-2": Dimmer,
    "HM-LC-Dim2T-SM": Dimmer,
    "HM-LC-Dim2T-SM-2": Dimmer,
    "HSS-DX": Dimmer,
    "263 132": Dimmer,
    "263 133": Dimmer,
    "263 134": Dimmer,
    "HM-Dis-TD-T": Switch,
    "HM-OU-CF-Pl": Switch,
    "HM-OU-CM-PCB": Switch,
    "HM-OU-CFM-Pl": Switch,
    "HM-OU-CFM-TW": Switch,
    "HM-LC-Sw1-PCB": Switch,
    "HM-LC-Sw1-Pl": Switch,
    "HM-LC-Sw1-Pl-2": Switch,
    "HM-LC-Sw1-Pl-3": Switch,
    "HM-LC-Sw1-Pl-DN-R1": Switch,
    "HM-LC-Sw1-Pl-DN-R2": Switch,
    "HM-LC-Sw1-Pl-DN-R3": Switch,
    "HM-LC-Sw1-Pl-DN-R4": Switch,
    "HM-LC-Sw1-Pl-DN-R5": Switch,
    "HM-LC-Sw1-Pl-CT-R1": Switch,
    "HM-LC-Sw1-Pl-CT-R2": Switch,
    "HM-LC-Sw1-Pl-CT-R3": Switch,
    "HM-LC-Sw1-Pl-CT-R4": Switch,
    "HM-LC-Sw1-Pl-CT-R5": Switch,
    "HM-LC-Sw1-Pl-OM54": Switch,
    "HM-LC-Sw1-DR": Switch,
    "HM-LC-Sw1-SM": Switch,
    "HM-LC-Sw1-SM-2": Switch,
    "HM-LC-Sw1-FM": Switch,
    "HM-LC-Sw1-FM-2": Switch,
    "HM-LC-Sw1-PB-FM": Switch,
    "HM-LC-Sw1-Ba-PCB": Switch,
    "HM-LC-Sw1-SM-ATmega168": Switch,
    "HM-LC-Sw1PBU-FM": Switch,
    "HM-LC-Sw2-SM": Switch,
    "HM-LC-Sw2-FM": Switch,
    "HM-LC-Sw2-FM-2": Switch,
    "HM-LC-Sw2-DR": Switch,
    "HM-LC-Sw2-DR-2": Switch,
    "HM-LC-Sw2-PB-FM": Switch,
    "HM-LC-Sw2PBU-FM": Switch,
    "HM-LC-Sw4-Ba-PCB": Switch,
    "HM-LC-Sw4-SM": Switch,
    "HM-LC-Sw4-SM-2": Switch,
    "HM-LC-Sw4-SM-ATmega168": Switch,
    "HM-LC-Sw4-PCB": Switch,
    "HM-LC-Sw4-PCB-2": Switch,
    "HM-LC-Sw4-WM": Switch,
    "HM-LC-Sw4-WM-2": Switch,
    "HM-LC-Sw4-DR": Switch,
    "HM-LC-Sw4-DR-2": Switch,
    "263 130": Switch,
    "263 131": Switch,
    "ZEL STG RM FZS": Switch,
    "ZEL STG RM FZS-2": Switch,
    "HM-LC-SwX": Switch,
    "HM-MOD-Re-8": Switch,
    "IT-Switch": Switch,
    "REV-Ritter-Switch": Switch,
    "HM-Sec-SFA-SM": Switch,
    "HM-ES-PMSw1-Pl": SwitchPowermeter,
    "HM-ES-PMSw1-Pl-DN-R1": SwitchPowermeter,
    "HM-ES-PMSw1-Pl-DN-R2": SwitchPowermeter,
    "HM-ES-PMSw1-Pl-DN-R3": SwitchPowermeter,
    "HM-ES-PMSw1-Pl-DN-R4": SwitchPowermeter,
    "HM-ES-PMSw1-Pl-DN-R5": SwitchPowermeter,
    "HM-ES-PMSw1-DR": SwitchPowermeter,
    "HM-ES-PMSw1-SM": SwitchPowermeter,
    "HM-ES-PMSwX": SwitchPowermeter,
    "HMW-IO-12-Sw7-DR": IOSwitch,
    "HMW-IO-12-Sw14-DR": HMWIOSwitch,
    "HMW-IO-12-FM": IOSwitch,
    "HMW-LC-Sw2-DR": IOSwitch,
    "HMW-LC-Bl1-DR": KeyBlind,
    "HMW-LC-Bl1-DR-2": KeyBlind,
    "HMW-LC-Dim1L-DR": KeyDimmer,
    "HmIPW-DRS4": IPWSwitch,
    "HmIPW-DRS8": IPWSwitch,
    "HmIPW-DRI32": IPWInputDevice,
    "HmIPW-DRI16": IPWInputDevice,
    "HmIPW-DRD3": IPWDimmer,
    "HmIPW-SPI": IPWMotionDection,
    "HmIPW-DRBL4": IPWKeyBlindMulti,
    "HMIP-PS": IPSwitch,
    "HmIP-PS": IPSwitch,
    "HmIP-PS-CH": IPSwitch,
    "HmIP-PS-PE": IPSwitch,
    "HmIP-PS-UK": IPSwitch,
    "HmIP-PCBS": IPSwitch,
    "HmIP-PCBS-BAT": IPSwitch,
    "HmIP-PMFS": IPSwitch,
    "HmIP-MOD-OC8": IPSwitch,
    "HmIP-DRSI4": IPSwitch,
    "HmIP-BSL": IPKeySwitchLevel,
    "HMIP-PSM": IPSwitchPowermeter,
    "HmIP-PSM": IPSwitchPowermeter,
    "HmIP-PSM-CH": IPSwitchPowermeter,
    "HmIP-PSM-IT": IPSwitchPowermeter,
    "HmIP-PSM-PE": IPSwitchPowermeter,
    "HmIP-PSM-UK": IPSwitchPowermeter,
    "HmIP-FSM": IPSwitchPowermeter,
    "HmIP-FSM16": IPSwitchPowermeter,
    "HmIP-BSM": IPKeySwitchPowermeter,
    "HMIP-BDT": IPKeyDimmer,
    "HmIP-BDT": IPKeyDimmer,
    "HmIP-FDT": IPDimmer,
    "HmIP-PDT": IPDimmer,
    "HmIP-PDT-UK": IPDimmer,
    "HM-Sec-Key": KeyMatic,
    "HM-Sec-Key-S": KeyMatic,
    "HM-Sec-Key-O": KeyMatic,
    "HM-Sec-Key-Generic": KeyMatic,
    "HM-Sen-RD-O": Rain,
    "ST6-SH": EcoLogic,
    "HM-Sec-Sir-WM": RFSiren,
    "HmIP-MOD-HO": IPGarage,
    "HmIP-MOD-TM": IPGarage,
    "HM-LC-RGBW-WM": ColorEffectLight,
    "HmIP-MIOB": IPMultiIO,
    "HM-DW-WM": Dimmer,
    "HM-LC-DW-WM": ColdWarmDimmer,
    "HB-UNI-RGB-LED-CTRL": ColorEffectLight,
}
```

**Comment by danielperna84** [comment]
@sander76 

There are HomeMatic devices which expose their operation mode via the Paramset description. In some case this has also been implemented here by looking at them during the instantiation of the device-object. See [this](https://github.com/danielperna84/pyhomematic/blob/b771ab8a0022ea4e6011fe433860a2b260a44891/pyhomematic/devicetypes/actors.py#L320) for example.

Could this approach work with the HDM-devices? If not, then I don't think it will be possible to fully support these devices with the current architecture of pyhomematic.

**Comment by sander76** [comment]
@danielperna84 Getting a basic Ease blind into the system is fairly easy. But the exact behaviour of the blind (whether it is able to do tilting of slats for example) is defined inside an OEM container. To get this value I send out a `setValue` command with `OEM` as key and a specific OEM-string. This does not return a usable response (unfortunately) but an event is emitted with the OEM-value. 
So when a device of ours is paired with the cloud-based homematic-IP app it sends out this OEM-command and waits for the event to come in before proceeding.

See below, my rough idea of how to do this in this package. Does this look like something you would consider accepting as an implementation ?

https://github.com/sander76/pyhomematic/blob/ease/pyhomematic/devicetypes/actors.py#L65

**Comment by danielperna84** [comment]
@sander76 

First off, I think the way the device has been engineered depending on that event isn't optimal. This means software controlling the device can't build it's own object based on the cached paramset data. That's different from every HomeMatic device I have seen until now. Why has it been implemented that way?

You approach would be ok I guess. I'm unsure if re-implementing the `event` method that way would actually work without breaking the one from the parent class. But it could work I think. I do see problems however with making use of that gathered information in Home Assistant. It would require to transform the entity AFTER it has been created already.

That being said, I'm currently working on a new variation of pyhomematic called [hahomematic](https://github.com/danielperna84/hahomematic) (to be used with the new HomeMatic integration). What's happening there is, that for all new devices all the VALUES-paramsets are cached on disk, and entities are created for all parameters the have the event-bit set. Now I don't know what's going on with the parameters of the HmIP-HDM1, but wouldn't that approach provide all required entities anyways? Maybe there would be some entities that don't do anything because of how the device is programmed. But if the parameters are enabled in the device, the user can use them, and otherwise hide / ignore them. 🤷‍♂️

Out of interest: to which channel has the `setValue` with `OEM` to be sent to? And it's confusing that the `OEM` parameter doesn't show up in the paramsets. I really wonder why this implementation has to be such an _extrawurst_. 🤔

Anyways, since I'm focussing my efforts on the new library now, I would prefer to get the device working there instead of here (although I still have to do the customization stuff). But if it's easy for someone to implement here, I'll accept the PR.

**Comment by sander76** [comment]
@danielperna84 

The moment we, as a company contacted EQ-3 for cooperation we already had some experience with motorized blinds (the PowerView system is also from us). From that we concluded it is -for many reasons- beneficial to have one motor being able to have different capabilities depending on how it is programmed in fabrication (one motor, many applications). One of these capabilities is enabling/disabling tilt functionality, but also what we call package position: Is the fabric stacked at the top, left, bottom etc etc (a functionality not available in HASS). So our HMIP-HDM2 motor is able to be deployed in more than 10 different blind products.

Looking back we may have done it in another way. But together with EQ-3 it was decided we could use an OEM container for setting these parameters. At the time we/I did not know getting parameters from an OEM container couldn't be done with a "simple" request-response mechanism.

> You approach would be ok I guess. I'm unsure if re-implementing the event method that way would actually work without breaking the one from the parent class. But it could work I think. I do see problems however with making use of that gathered information in Home Assistant. It would require to transform the entity AFTER it has been created already.

The idea behind my implementation is that initialization/creating of the entity will only be complete after the OEM event has been received. But I really don't like the time.sleep function as it just blocks everything.

> That being said, I'm currently working on a new variation of pyhomematic called hahomematic (to be used with the new HomeMatic integration). What's happening there is, that for all new devices all the VALUES-paramsets are cached on disk, and entities are created for all parameters the have the event-bit set. Now I don't know what's going on with the parameters of the HmIP-HDM1, but wouldn't that approach provide all required entities anyways? Maybe there would be some entities that don't do anything because of how the device is programmed. But if the parameters are enabled in the device, the user can use them, and otherwise hide / ignore them. 🤷‍♂️

Unfortunately no. Currently the VALUES paramset do not have our product_id and package position stored. It can only be retrieved by getting that OEM container. I don't like that either, but I am trying to get that changed and if I manage we'll all be fine. If I can't I'd still really like this products to be implemented: Having all these blinds implemented is a big plus for the DIY homematic community (and for us too ;-) )

> Out of interest: to which channel has the setValue with OEM to be sent to? And it's confusing that the OEM parameter doesn't show up in the paramsets. I really wonder why this implementation has to be such an extrawurst. 🤔

I do not send it to a channel. I send it to a "vendor_id". Which is the EQ3 way to implement custom products.

> Anyways, since I'm focussing my efforts on the new library now, I would prefer to get the device working there instead of here (although I still have to do the customization stuff). But if it's easy for someone to implement here, I'll accept the PR.

I'll have a look at your new library. I will do some thinking on implementing this further and maybe make a PR.
When do you think hahomematic will replace pyhomematic ?

**Comment by danielperna84** [comment]
@sander76 

Thinking about it, it does start to make more sense why that OEM-thing has been done. The devices I was talking about with variable functionality allow the __user__ to modify how the device behaves in the CCU UI. For your blind-motors this isn't the case - it's predefined during production as you have said. So I get that now. Just to give you an example about what I was thinking about, have a look at the paramsets of the [HM-ES-TX-WM](https://github.com/danielperna84/pydevccu/blob/471ed230699c3014884c3d0dff23793ae8f890e9/pydevccu/paramset_descriptions/HM-ES-TX-WM.json#L123). Although I have to admit, that in this case the `VALUES` paramset still always contains all parameters instead of excluding inactive ones. I thought it was different. So `hahomematic` will also create the entities for parameters that are unavailable. But the inactive ones can just be ignored by the user in my opinion. 🤷‍♂️

Another example in this direction would be the [HMW-IO-12-Sw14-DR](https://github.com/danielperna84/pydevccu/blob/471ed230699c3014884c3d0dff23793ae8f890e9/pydevccu/paramset_descriptions/HMW-IO-12-Sw14-DR.json#L149). In this case though it seems to be more like I thought it would always be. The `BEHAVIOUR` parameter has the `0x04`-bit (_transform flag_) set. And at least in my programmatically generated JSON I have linked the `VALUES` paramsets all have the `FREQUENCY` parameter (`FLOAT`). I believe if the channel was set to digital mode, there would be a `BOOL` parameter, probably called `STATE`. So __that's__ how I would have hoped all devices (configurable by the user) would work. And maybe you can do something similar in future versions of your device.

> The idea behind my implementation is that initialization/creating of the entity will only be complete after the OEM event has been received. But I really don't like the time.sleep function as it just blocks everything.

Yeah, that's not how it should be. I'll think about this a bit more and how I will handle that in `hahomematic`. For pyhomematic I will not support this myself. But I'm free to accept working solutions.

> Unfortunately no. Currently the VALUES paramset do not have our product_id and package position stored.

Are these two parameters even _useful_ for automations? And could be please explain more how the OEM-variants are different from each other? A few posts above you said: _which means -among other things- that sometimes they make use of both primary and secondary levels and others times only primary_.

The paramset-description posted here does include [LEVEL_2](https://github.com/danielperna84/pydevccu/blob/471ed230699c3014884c3d0dff23793ae8f890e9/pydevccu/paramset_descriptions/HmIP-HDM1.json#L780). What would happen if Home Assistant would try to set a new `LEVEL_2` when the device doesn't support it? I assume it would _only_ result in an exception (XML-RPC). So essentially I don't see any problems in just always implementing `LEVEL_2` for example. For devices that don't support it, it just wouldn't work because the devices can't handle the command. The only _optimization_  I would see would be to reliably reflect the tilt-support (or whatever else) so Home Assistant would display that correctly in the UI. 🤷‍♂️

Would the `OEM` event also include additional parameters which are not included in the paramset I already have? Or more specifically, could you provide an example value (you called it _OEM-value_) that would be transmitted? And would you be able to create a map that reflects which functionality is available for any possible OEM-value?

> I do not send it to a channel. I send it to a "vendor_id". Which is the EQ3 way to implement custom products.

In your [implementation](https://github.com/sander76/pyhomematic/blob/dd3e126a490552bf48398469097a0cdb41f530d3/pyhomematic/devicetypes/actors.py#L85) you are sending `OEM` to `self.ADDRESS`. So in practice this would be the regular address without the channel suffix. So for a device with `aabbcc` with the children `aabbcc:0` and `aabbcc:1`, the `setValue` would be pointed at `aabbcc`. Is this correct`?

> I'll have a look at your new library. I will do some thinking on implementing this further and maybe make a PR.
> When do you think hahomematic will replace pyhomematic ?

I'll inform you when the library is ready for _custom_ devices. 👍

And `hahomematic` will not directly replace `pyhomematic`. It's intended to be the foundation for a completly new integration (with support for Home Assistant _devices_, setup from UI etc.). At first I imagine this to be a custom component early adopters can use for testing. Then once everything is stable I hope Home Assistant will allow this new integration to replace the current one. Which would be a __huge__ breaking change for HomeMatic users. But I don't see any other way. The current architecture of `pyhomematic` and the HA integration come with limitations that can't be worked around anymore without breaking at least some parts. Hence I believe a fresh start without the old problems is the better solution in the long run.

That being said, I need [help](https://github.com/danielperna84/hahomematic/issues/1) with the new integration. So as long as I don't get support from anyone, there's nothing I can say about the new integration becoming available. I _hope_ it will happen in 2021 though. 😉

**Comment by sander76** [comment]
I'll need some time to absorb everything you've written, but in the end all the above effort is about getting a proper representation of the product in Hass. 

For our blinds it doesn't matter if there is tilt functionality in the UI. It would also just ignore a LEVEL_2 command if not relevant. But I hope in the future the cover component will be developed further, by not only adding buttons, but maybe sliders (like it is in the HmIP cloud app). And the ability to get a proper visualization where my package_position will be useful. 
So maybe just for now I should just ignore this and get proper support for my OEM parameters in the VALUES paramset. This would make it all much easier.

**Comment by danielperna84** [comment]
> So maybe just for now I should ... get proper support for my OEM parameters in the VALUES paramset. This would make it all much easier.

Yes, that would be great! 👍 It would also be ok if it's just in a `MASTER` paramset, like `BEHAVIOR` seen on the HMW device mentioned above. After all it's not a value the user should mess around with. So `MASTER` might make more sense.

**Comment by danielperna84** [comment]
@sander76 

There has been great progress in the new [hahomematic](https://github.com/danielperna84/hahomematic) based integration. Feel free to give it a try following [these](https://github.com/danielperna84/custom_homematic/wiki/Installation) instructions to install the custom integration via HACS. You may then open an issue in the hahomematic repo regarding the support for these special devices. 👍

**Comment by sander76** [comment]
Hi Daniel,
Great to hear! Unfortunately I am no longer working for Hunter Douglas and the Ease/HmIP blinds, but I've still got some in my house and find it useful to have them integrated. But working on it might take a little longer now.

Currently I am using both the cloud based and the local (raspberrymatic plugin) implementation in Hass, but looking forward to moving it all to local !

**Comment by danielperna84** [comment]
The new integration should one day replace what currently is the local plugin you're using with raspberrymatic. So you'll benefit from giving some feedback about how these devices work with the current state of the new integration. 😉

**Comment by sander76** [comment]
I understand and totally agree !

**Comment by zngguvnf** [comment]
Just for the record:

Today I finally got my new pleated blinds which are based on HMiP-HDM-2.
As it says here, they don't work with the old integration but I can report that they worked immediately with the new integration (v0.26.3).

I just wanted to report this briefly and say thank you very much. If there is anything you would like me to test specifically regarding the blinds, please let me know. I am happy if I can help.

**Comment by sander76** [comment]
That is great to hear. The thing is that these exact same motors are used in a venetian blind product, meaning they can facilitate tilting of slats. I wonder how your product shows up in hass?

**Comment by danielperna84** [comment]
@zngguvnf 

Do you mind providing the device data so I can include it in my [pydevccu](https://github.com/danielperna84/pydevccu) projekt. You can use [this](https://github.com/danielperna84/pydevccu/blob/master/pydevccu/get_device_data.py) script to get the files.

**Comment by zngguvnf** [comment]
Here you go:

[device_descriptions/HmIP-HDM2.json](https://gist.github.com/zngguvnf/85db9af80f8241142b046e47c35bdb00)
[paramset_descriptions/HmIP-HDM2.json](https://gist.github.com/zngguvnf/cca3bd300f0a78bd87a07faf7e45e371)

**Comment by danielperna84** [comment]
Closing this issue, as blind-support is pretty robust with the [new integration](https://github.com/danielperna84/custom_homematic). If there still are problematic devices, please report [here](https://github.com/danielperna84/hahomematic).
