### ISSUE TITLE
HmIP-WRC6

### ISSUE THREAD

**Issue by regnets** [danielperna84/pyhomematic#343]
As described in #28, I created the necessary files for the homematic ip six button wall switch.

Here is the gist:
https://gist.github.com/regnets/56dc83296af35d5cda975de63626bee5

**Comment by danielperna84** [comment]
The device should already be supported: https://github.com/danielperna84/pyhomematic/blob/6eb9effd5f5800f0136f527051251b88463c99c0/pyhomematic/devicetypes/misc.py#L142

Since it's a button-device no entities for it will be generated. In Home Assistant these devices are used by listening for `homematic.keypress` events.

**Comment by regnets** [comment]
Oh, i wasn't aware of this, let me check if i can see the Battery Level as a sensor, than i will close this feature request.

**Comment by danielperna84** [comment]
It might be, that the battery level isn't implemented. But apart from that the events should be working.

**Comment by regnets** [comment]
Yeah, also closed.
