### ISSUE TITLE
HmIP-MP3P

### ISSUE THREAD

**Issue by regnets** [danielperna84/pyhomematic#345]
As described in #28, I created the necessary files for the homematic ip wireless MP3 door bell.

Here is the gist:
https://gist.github.com/regnets/9c7913758ea889caf2d2e8e59f5a0134

**Comment by Remko76** [comment]
I also now have this doorbell, what help us required for the implementation in home assistant. Anything I can do to get this working?

**Comment by danielperna84** [comment]
> what help us required for the implementation in home assistant

We need somebody who understands how pyhomematic works, understands the information contained in the posted JSON files, and knows how a sensible integration should look like. This isn't a simple device like a switch or sensor. Some features might not even be possible to integrate in the Home Assitant UI at all. But that really depends on what the device can do and how its represented in the CCU.

**Comment by Remko76** [comment]
Hmmm... Sounds like a bit over my head at the moment. I will need to read and dig a bit more for this. I have seen there is already another MP3 Homematic devices, which is supported as far as I have seen.
I will just try to dig around and see if I can find anything. Until then I'll first use the device but environment variables and programs on the CCU. That way I should already be able too at least get it working for now and use the fancy colours and sounds. 
But I am also not entirely sure yet on what I want to use it for, besides the simple door bell. The are probably tons of ideas for colours and sounds based on states off devices, just need to find the use case for it...;)

**Comment by danielperna84** [comment]
In general you should already be able to control the device by using the [set_device_value](https://www.home-assistant.io/integrations/homematic/#services) or `put_paramset_value` services. In the JSON you'll find multiple [VALUES](https://gist.github.com/regnets/9c7913758ea889caf2d2e8e59f5a0134#file-paramset_descriptions-hmip-mp3p-json-L558) sections. These are the parameters that can be controlled. How they can be controlled depends on the `OPERATIONS` and `Type` attributes.  It's a bitmask, which is explained in the [XML-RPC API](https://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/HM_XmlRpc_API.pdf) documentation.

So as an example on channel 3 there's the parameter [LEVEL](https://gist.github.com/regnets/9c7913758ea889caf2d2e8e59f5a0134#file-paramset_descriptions-hmip-mp3p-json-L7896) of type `FLOAT` and an `OPERATIONS` value of 7. 7 is 1 + 2 + 4, so it's read, write and event. Because it's writable, you can send a float value (0.0 - 1.01) to it to make it do something.

Manually in Python 3 you would control it like this:

```python
from xmlrpc.client import ServerProxy
p = ServerProxy("http://1.2.3.4:2010") # IP address of the CCU
p.setValue("aabbccdd:3", "LEVEL", 0.5) # aabbccdd is the device ID
current_value = p.getValue("aabbccdd:3", "LEVEL")
```

The `set_device_value` service mentioned above really is just a wrapper to call the `setValue` method which you see in the Python code. So everything you manage to do in Python can be done via manual service calls. For the parameters of type `ENUM` you'll also see a list of values in the JSON. For those you use the `setValue` method and a value from 0 to N. The elements in those lists are counted from 0 upwards. So it look like sending a number (0, 1, 2...) at the parameter `SHORT_OUTPUT_BEHAVIOUR` could make the device play a sound.

Hope this helps.

**Comment by creatvty** [comment]
Hey, I have been reading along here for a bit. Recently I also acquired this device and would be eager to use it in home assistant. Unfortunately I am only just getting a glimpse of home assistant / pyhomematic development but I am trying to figure it out. This is of course a more complex device and not the best for easing into...
I think I will try a few things and see where I can get. Probably I will start by trying to get the light to work. Wish me luck.

**Comment by Plaethe** [comment]
> Hey, I have been reading along here for a bit. Recently I also acquired this device and would be eager to use it in home assistant. Unfortunately I am only just getting a glimpse of home assistant / pyhomematic development but I am trying to figure it out. This is of course a more complex device and not the best for easing into... I think I will try a few things and see where I can get. Probably I will start by trying to get the light to work. Wish me luck.

Any updates on the support of the HmIP-MP3P?

**Comment by danielperna84** [comment]
This device should now be supported by the [new integration](https://github.com/danielperna84/custom_homematic).
