### ISSUE TITLE
HM-Sec-SD-2-Team

### ISSUE THREAD

**Issue by Plazmin** [danielperna84/pyhomematic#352]
I have a team of smoke detectors. Unfortunately, the appropriate entity does not appear in home assistant. Smoke detector entities show up. Where is the problem? Are teams supported by homematic integration? I am using debmatic. 
I have one more question. What value should the homematic.ccu3 entity have and what does it mean? For me it is "0"

My HA configuration.yaml
homematic:
  interfaces:
    rf:
      host: 192.168.12.44
      resolvenames: json
      username: Admin
      password: password123
    wired:
      host: 192.168.12.44
      port: 2000
      resolvenames: json
      username: Admin
      password: password123
    ip:
      host: 192.168.12.44
      port: 2010
    groups:
      host: 192.168.12.44
      port: 9292
      resolvenames: json
      username: Admin
      password: password123
      path: /groups
  hosts:
    ccu3:
      host: 192.168.12.44
      port: 2001
      username: Admin
      password: password123

**Comment by danielperna84** [comment]
I don't know if they should be supported as a team. I haven't done the implementation. In general I would expect them to appear by adding a second interface with the `/groups` path. But those typically are for thermostat-groups. So that might not work for smoke detectors.

> What value should the homematic.ccu3 entity have and what does it mean? For me it is "0"

That's the number of service messages. So `0` is the ideal state. You could have an automation that watches this value and sends you a notification in case new service messages appear.

**Comment by Plazmin** [comment]
> I don't know if they should be supported as a team. I haven't done the implementation. In general I would expect them to appear by adding a second interface with the `/groups` path. But those typically are for thermostat-groups. So that might not work for smoke detectors.

I think they should be supported as a team. Changing the state of any smoke detector from the team causes a change in the state of HM-Sec-SD-2-Team. So it is enough to observe the state of only one entity to know if there is fire in the apartment. Team is semi-automatically created during teach-in smoke detectors. To my knowledge it has nothing to do with groups. Would it be problematic to implement this? Are you able to do this?

**Comment by danielperna84** [comment]
> Changing the state of any smoke detector from the team causes a change in the state of HM-Sec-SD-2-Team. So it is enough to observe the state of only one entity to know if there is fire in the apartment.

Just to make this clear: if you have smoke detector A and B, which together form the team C, and A detects a fire, B and C will change their state as well? If so, what's the practical benefit of monitoring C if B gets updated as well? Just monitor A and you'll always get notified because of the internal teaming. 🤷‍♂️ 

> Would it be problematic to implement this?

It can only be implemented if the CCU exposes these teams as some sort of devices.

> Are you able to do this?

No, because I don't have devices to work with.

**Comment by Plazmin** [comment]
You are right, it is logical. There is a record in the documentation: "The Homematic Wireless Smoke Alarm HM-Sec-SD-2 is intended for use in a network with other wireless smoke alarms of the same type. This provides an extra level of safety: In the event of fire the wireless smoke alarm simultaneously sends an alarm to all devices of the same type that are located within wireless range. Thus, you can react early enough to a fire that may still be some distance away, perhaps in an-other room on a different floor of the building." 
However, I do not understand for what purpose an additional device is created in CCU3.  I have too little knowledge on this topic. What do you think about it?

![ccu](https://user-images.githubusercontent.com/62091912/99105030-1af48080-25e2-11eb-9f39-a83edeaade68.png)
