### ISSUE TITLE
HMGeneric.getValue Exception

### ISSUE THREAD

**Issue by simonszu** [danielperna84/pyhomematic#39]
Hi,

i am using pyhomematic to get some values for my Home Assistant Setup, namely the current energy usage of my flat via a HM-ES-TX-WM and a ES-Fer. 
Depending on which type of sensor connected to the HM-ES-TX-WM the unit provides some values to read. With the ES-Fer connected, it provides ENERGY_COUNTER, if it has one of the two other sensors connected, it provides GAS_ENERGY_COUNTER or GAS_POWER as a value to read. 

Somehow, it does always expose all three values via homematic as a key, but only one of them has an actual value, because only one of three sensors can be connected at the same time. 
So pyHomematic tries to query all keys at the start of HASS, and shows two exceptions because it tries to read two keys without value. This does not affect the startup of HASS or the reading of the existing values after that, but i just want to let you know about this behaviour. 

Maybe you can implement a routine which knows about this homematic behaviour, and does check if a key has a value first, instead of assuming that homematic always has a value for every exposed key.

**Comment by pvizeli** [comment]
Yeah that is not be nice but If I try to check if the value readable, I produce the same exception to. Homematic need to add a API function for that and we can use it.

The home-assistant implementation is use autodiscovery and we need to create all possible device. The user can make it unvisible if they want not show on UI.

Can you put your log to here?

**Comment by simonszu** [comment]
This is the log entry when home-assistant/pyhomematic try to access the gas sensor, which is not connected to the HM-ES-TX-WM

```
INFO:pyhomematic.devicetypes.generic:HMGeneric.getValue: key = 'RSSI_DEVICE'
INFO:pyhomematic.devicetypes.generic:HMGeneric.getValue: key = 'GAS_ENERGY_COUNTER'
ERROR:pyhomematic.devicetypes.generic:HMGeneric.getValue: Exception: <Fault -1: 'Failure'>
```
The access to the sensor for the digital electric current counter is the same, only the key in the second line differs.

**Comment by danielperna84** [comment]
As pvizeli said, the problem lies in the way the XML-RPC works. We don't know in advance which keys we can use to ask for values, so we have to try each one that's available. Performing the request with a key that is not "active" in your setup leads to the exception. But to know it is not active we have to do the request. So, yeah, that's a typical "Henne-Ei"-Problem.
If I understood correctly, this only happens while HASS is starting. Afterwards the values get updated through events, and I assume the CCU won't send events for inactive keys. So it's fully functional, and there are only two ERROR-message in the logs. Am I correct? If so, I would close this issue and mark it _wontfix_.
