### ISSUE TITLE
HmIP-FALMOT-C12: Missing channels 13 - 16

### ISSUE THREAD

**Issue by richardklingler** [danielperna84/pyhomematic#391]
The HmIP_FALMOT-C12 is partially supported as the channels 1 - 10 are available as heating levels ranging from 0.0 to 1.0.

But the FALMOT-C12 has 6 more channels which signal to the outside for controlling additional pumps and boilers which are not available at the moment:

Channel 11: Heating level 11, 0.0 - 1.0
Channel 12: Heating level 12, 0.0 - 1.0
Channel 13: Boiler control, binary on/off
Channel 14: Pump control, binary on/off
Channel 15: Dehumidifier control, binary on/off
Channel 16: Heating/Cooling, binary on/off

Can I somehow extend the device_description.json and build a new integration version for testing on my FALMOT-C12 system?
I don't seem to find any references how to achieve this (o;

thanks in advance
richard

**Comment by richardklingler** [comment]
Another thing:

The Homematic integration lists a binary sensor for the HmIP-FALMOT-C12 floor heating controller which doesn't exist at all:

- binary_sensor low_bat

**Comment by Knechtie** [comment]
Hi Richard,

I've added channel 11 & 12 for the RF-version in my pull request for the wired box.
But I could not find out how to add channel 13-16. I guess it's not possible because the channels can only be paired with actuators in the CCU and are therefore not available as "Sensor"/State. Unlike the valve level value of other channels, there is no channel state parameter available for channel 13-16 (see page 1835 [here](https://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/HmIP_Device_Documentation.pdf)). Maybe @danielperna84 can say more about this as I don't know much about this stuff.

As "workaround" I would create a template sensor/automation which evaluates if one of the valve positions is >0.0 e.g. to start the pump.


Philipp

**Comment by danielperna84** [comment]
@Knechtie 

Please post the device data as decribed [here](https://github.com/danielperna84/pyhomematic/issues/28#issue-162335385) so I can have a look at it. 👍

**Comment by Knechtie** [comment]
@danielperna84 

https://gist.github.com/Knechtie/017c4f5a715134a3dcec9de35b768dae

**Comment by danielperna84** [comment]
@Knechtie 

By looking at the paramset description I can say that there certainly are no values pyhomematic / Home Assistant can work with for the channels 13 - 16. So beyond your PR there's nothing we can do.
