### ISSUE TITLE
Expose Homematic rooms as entities

### ISSUE THREAD

**Issue by pannal** [danielperna84/pyhomematic#405]
**Describe the solution you'd like**
Please correct me if I'm wrong, but in the Homematic interface I can control all climate entities using rooms. Those rooms are exposed via XML-RPC as well.

Would it be possible to do the same for pyhomematic? I might have multiple sensors and actors in one room and I want to control the room as a whole, as I would with the room interface of the CCU2 Homematic WebUI.

This would result in the following climate entities in HA, for rooms "Living Room" and "Bathroom":
`climate.living_room`
`climate.bathroom`

That way a combination of cooling and heating entities could possibly be controlled using one climate widget.

Thanks

**Comment by danielperna84** [comment]
> Those rooms are exposed via XML-RPC as well.

Could you go into detail about this? I have never seen the rooms being available via XML-RPC. They probably are available via the XML-API Addon for the CCU. But pyhomematic won't include functionality that depends on 3rd party plugins for the CCU.

Those details might also be available via JSON-RPC. But even then I wouldn't want to include this, because Homegear (which quite a few users are using) neither has the XML-API addon nor the JSON-RPC API like the CCU provides.

So essentially this would result in inconsistent experiences for users using different HomeMatic _hubs_.

That being said, pyhomematic is strictly using the XML-RPC API. So even if we get Room-IDs through some other way, I doubt it's possible to use control rooms using these IDs, as they probably are unknown to the API.

**Comment by pannal** [comment]
I wasn't aware there's a different XML API other than the one provided by the XML API addon. Sorry for that, my experience with homematic is about one week today.

Rooms are definitely a helpful feature that even spans heating groups, but I totally understand your decision to not support 3rd party addons on the CCU.

Thank you for your awesome work.
