### ISSUE TITLE
HmIP-SCTH230 - Formatting of ppm value

### ISSUE THREAD

**Issue by eikowagenknecht** [danielperna84/pyhomematic#449]
**Home Assistant version (if applicable):**
2021.11.5

**Describe the bug**
![image](https://user-images.githubusercontent.com/1475672/144467631-343a4df4-9c99-47fb-929f-0b89ab2a0dd4.png)
The upper two sensors are Netatmo, the third the HmIP-SCTH230.

As you can see, there is always an appended ",0" for the value, suggesting more precision than it has.

**Expected behavior**
In the CCU only integers are shown:
![image](https://user-images.githubusercontent.com/1475672/144468262-84540def-eb83-4d45-9288-683c3b55a2cb.png)

As this is fake precision, it would be better to use integers as well.

**Comment by danielperna84** [comment]
I think this is an UI issue of Home Assistant. It seems as it is displaying decimals for values greater than 999, even though the thousands-separator would be sufficient.

**Comment by eikowagenknecht** [comment]
It also happens <999:

![image](https://user-images.githubusercontent.com/1475672/148824596-9c72c16f-ce3d-4055-ab0f-c0a9471c4407.png)

And since the Netatmo integrations manages to show it without ",0" I would say it's integration specific.

**Comment by danielperna84** [comment]
Well, it does not in the screenshot above. That's why I thought this might be the reason. 🤔 Nevertheless, I still think this is an issue on the Home Assistant side. In pyhomematic we just forward the value we get from the CCU. How are the values displayed with the new custom integration in comparison?

**Comment by eikowagenknecht** [comment]
Just installed the new hahomematic custom integration and it shows them also with the appended ",0":

![image](https://user-images.githubusercontent.com/1475672/148848033-bfacd799-f4d4-4a6b-b26f-6909830ae298.png)

**Comment by danielperna84** [comment]
I think [this](https://github.com/home-assistant/frontend/blob/e94fc493b8b49ee5e85ecdf1db664282fa67efd1/src/common/number/format_number.ts#L20) is where the formatting is coming from. But I have never worked with the UI part of Home Assistant. So I can't help with that. And I don't know how it would be possible to tell HA to render certain numbers differently.

**Comment by eikowagenknecht** [comment]
How is the value reported from hahomematic side? https://github.com/home-assistant/frontend/blob/e94fc493b8b49ee5e85ecdf1db664282fa67efd1/src/common/number/format_number.ts#L99 says it's keeping the trailing zeros if they are present in a string numeric value.

**Comment by danielperna84** [comment]
It's a [FLOAT](https://github.com/danielperna84/pydevccu/blob/39171614da91d09b983f71aebe0ba10b4d7d6b23/pydevccu/paramset_descriptions/HmIP-SCTH230.json#L514). So it's really the device reporting it this way.

**Comment by eikowagenknecht** [comment]
So it's technically correct to add the trailing zero, I see. But doesn't make much sense because the device only ever returns values with a leading zero and even the original web interface doesn't show it (see screenshot above). Any idea how this could be handled? Is there a possibility included in hahomematic for device specific workarounds for this kind of weirdness?

**Comment by danielperna84** [comment]
Well, as sooner or later the pyhomematic based integration will be obsolete anyways, I won't address this minor cosmetic issue. Feel free to create an issue for hahomematic. Maybe Markus has an idea on how to solve this elegantly.

The correct way to solve this would actually be, that eq3 changes the type of the parameter to be an integer. But that will probably never happen. We can't use any generic approach for this like always converting floats to ints, because obviously other float-based parameters make use of the decimals. So this would be some sort of custom device (like blinds or thermostats). And honestly, I don't think this is worth the effort.
