### ISSUE TITLE
Wired unit HMW-IO-12-Sw7-DR not fully recognized

### ISSUE THREAD

**Issue by Eckart0** [danielperna84/pyhomematic#458]
Wired Homematic devices HMW-IO-12-Sw7-DR are not fully recognized.
Only the output channels 13-19 are shown, but the first 12 input channels aren't recognized.

This is a really big problem because all the push-buttons in wired Homematic installations run via these push-buttons. So Home Assistant cannot be used in such installations.

Is there a workaround for this? Or is a newer version of the Homematic integration to be expected?

Many greetings, Eckart

**Comment by danielperna84** [comment]
1. Did you take [this](https://www.home-assistant.io/integrations/homematic/#devices-with-buttons) into consideration?
2. New integration is being developed and can be found here: https://github.com/danielperna84/custom_homematic

**Comment by Eckart0** [comment]
Thank you for the quick reply.

So if I want to gradually move my automations from the CCU to Home Assistant, do I have to manually make such an entry in automatisation.yaml for each button - and then differentiated according to PRESS_SHORT / PRESS LONG? Can't this be done automatically in the Homematic integration? At least optionally?

Otherwise this is a really tedious and error-prone task.

Many greetings, good night,
Eckart

**Comment by danielperna84** [comment]
What you are asking for is technically not possible with the integration. Home Assistant doesn't know which buttons and their possible actions are available on the CCU. Home Assistant just reacts to events once the arrive. Hence it's not possible to prepare anything.

That being said, you have to recreate your automations from hand in any case because in HA everything will be different than on the CCU. Therefore configuring the trigger is the least of your _problems_.

Keep in mind though, that if you are using "Direktverknüpfungen" with your buttons, I don't recommend to migrate them to HA. Direktverknüpfungen are a lot more performant and always work, independently of Home Assistant.
