### ISSUE TITLE
exceptions / disconnects

### ISSUE THREAD

**Issue by buxit** [danielperna84/pyhomematic#76]
i am wondering if there is a way to handle device disconnects or other connection problems in home assistant / pyhomematic.

i'd like to be notified about any device disconnects or any problems with _ccu_ <-> _device_ and _ccu_ <-> _home assistant_ communication via an event that can be automated.

there might be infrastructure for this already, but i was not able to find any information.

**Comment by danielperna84** [comment]
With _ccu <-> device_ you mean the communication between the CCU and a thermostat or whatever? If so, the CCU has the "Servicemeldungen". These aren't directly visible in HASS (yet, it would be possible though if someon would implement it), but the ccu-entity within HASS always has a numeric value, which corresponds to the total count of such service messages. So if it's always 0 and then turns to 1 you know, that at least some sort of error has occurred. That way you know you should have a look at the CCU and check which error has happened.

The _ccu <-> hass_ connection is hard to monitor. A dropped connection usually results in your hass-devices not updating anymore, since the CCU stops sending the event-data to hass. But the CCU does not send a "we had a dropped connection"-message. And the CCU also lacks som sort of "ping"-method which we could use to check if the connection is still alive. So in that case you only have the workaround to have an automation that fires as soon as some sensor hasn't changed for time X. A brightness-sensor for example which is configured to periodically send the brightness. Such a sensor should change its value a few times across a whole if it's near a window. Or something similar, like a sensor measuring the power usage of the house, which never is 0W if you have a CCU running.
